'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace AccountServicio
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DUsuario", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DUsuario
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ApellidosField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EmailField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaModField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaNacimientoField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaRegField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdUsuarioField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombresField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PasswordField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RolField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SexoField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As Boolean
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Apellidos() As String
            Get
                Return Me.ApellidosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ApellidosField, value) <> true) Then
                    Me.ApellidosField = value
                    Me.RaisePropertyChanged("Apellidos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Descripcion() As String
            Get
                Return Me.DescripcionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionField, value) <> true) Then
                    Me.DescripcionField = value
                    Me.RaisePropertyChanged("Descripcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Email() As String
            Get
                Return Me.EmailField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EmailField, value) <> true) Then
                    Me.EmailField = value
                    Me.RaisePropertyChanged("Email")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaMod() As Date
            Get
                Return Me.FechaModField
            End Get
            Set
                If (Me.FechaModField.Equals(value) <> true) Then
                    Me.FechaModField = value
                    Me.RaisePropertyChanged("FechaMod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaNacimiento() As Date
            Get
                Return Me.FechaNacimientoField
            End Get
            Set
                If (Me.FechaNacimientoField.Equals(value) <> true) Then
                    Me.FechaNacimientoField = value
                    Me.RaisePropertyChanged("FechaNacimiento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaReg() As Date
            Get
                Return Me.FechaRegField
            End Get
            Set
                If (Me.FechaRegField.Equals(value) <> true) Then
                    Me.FechaRegField = value
                    Me.RaisePropertyChanged("FechaReg")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdUsuario() As System.Guid
            Get
                Return Me.IdUsuarioField
            End Get
            Set
                If (Me.IdUsuarioField.Equals(value) <> true) Then
                    Me.IdUsuarioField = value
                    Me.RaisePropertyChanged("IdUsuario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nombres() As String
            Get
                Return Me.NombresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombresField, value) <> true) Then
                    Me.NombresField = value
                    Me.RaisePropertyChanged("Nombres")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Password() As String
            Get
                Return Me.PasswordField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PasswordField, value) <> true) Then
                    Me.PasswordField = value
                    Me.RaisePropertyChanged("Password")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Rol() As Integer
            Get
                Return Me.RolField
            End Get
            Set
                If (Me.RolField.Equals(value) <> true) Then
                    Me.RolField = value
                    Me.RaisePropertyChanged("Rol")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sexo() As Boolean
            Get
                Return Me.SexoField
            End Get
            Set
                If (Me.SexoField.Equals(value) <> true) Then
                    Me.SexoField = value
                    Me.RaisePropertyChanged("Sexo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="AccountServicio.IAccountServicio")>  _
    Public Interface IAccountServicio
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAccountServicio/DoWork", ReplyAction:="http://tempuri.org/IAccountServicio/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAccountServicio/DoWork", ReplyAction:="http://tempuri.org/IAccountServicio/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAccountServicio/Signin", ReplyAction:="http://tempuri.org/IAccountServicio/SigninResponse")>  _
        Function Signin(ByVal Usuario As AccountServicio.DUsuario) As AccountServicio.DUsuario
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAccountServicio/Signin", ReplyAction:="http://tempuri.org/IAccountServicio/SigninResponse")>  _
        Function SigninAsync(ByVal Usuario As AccountServicio.DUsuario) As System.Threading.Tasks.Task(Of AccountServicio.DUsuario)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAccountServicio/Register", ReplyAction:="http://tempuri.org/IAccountServicio/RegisterResponse")>  _
        Function Register(ByVal Usuario As AccountServicio.DUsuario) As AccountServicio.DUsuario
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IAccountServicio/Register", ReplyAction:="http://tempuri.org/IAccountServicio/RegisterResponse")>  _
        Function RegisterAsync(ByVal Usuario As AccountServicio.DUsuario) As System.Threading.Tasks.Task(Of AccountServicio.DUsuario)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IAccountServicioChannel
        Inherits AccountServicio.IAccountServicio, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class AccountServicioClient
        Inherits System.ServiceModel.ClientBase(Of AccountServicio.IAccountServicio)
        Implements AccountServicio.IAccountServicio
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements AccountServicio.IAccountServicio.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements AccountServicio.IAccountServicio.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
        
        Public Function Signin(ByVal Usuario As AccountServicio.DUsuario) As AccountServicio.DUsuario Implements AccountServicio.IAccountServicio.Signin
            Return MyBase.Channel.Signin(Usuario)
        End Function
        
        Public Function SigninAsync(ByVal Usuario As AccountServicio.DUsuario) As System.Threading.Tasks.Task(Of AccountServicio.DUsuario) Implements AccountServicio.IAccountServicio.SigninAsync
            Return MyBase.Channel.SigninAsync(Usuario)
        End Function
        
        Public Function Register(ByVal Usuario As AccountServicio.DUsuario) As AccountServicio.DUsuario Implements AccountServicio.IAccountServicio.Register
            Return MyBase.Channel.Register(Usuario)
        End Function
        
        Public Function RegisterAsync(ByVal Usuario As AccountServicio.DUsuario) As System.Threading.Tasks.Task(Of AccountServicio.DUsuario) Implements AccountServicio.IAccountServicio.RegisterAsync
            Return MyBase.Channel.RegisterAsync(Usuario)
        End Function
    End Class
End Namespace
