'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace CiudadServicio
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DCiudad", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DCiudad
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdCiudadField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdPaisField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PaisField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Descripcion() As String
            Get
                Return Me.DescripcionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionField, value) <> true) Then
                    Me.DescripcionField = value
                    Me.RaisePropertyChanged("Descripcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdCiudad() As System.Guid
            Get
                Return Me.IdCiudadField
            End Get
            Set
                If (Me.IdCiudadField.Equals(value) <> true) Then
                    Me.IdCiudadField = value
                    Me.RaisePropertyChanged("IdCiudad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdPais() As System.Guid
            Get
                Return Me.IdPaisField
            End Get
            Set
                If (Me.IdPaisField.Equals(value) <> true) Then
                    Me.IdPaisField = value
                    Me.RaisePropertyChanged("IdPais")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Pais() As String
            Get
                Return Me.PaisField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PaisField, value) <> true) Then
                    Me.PaisField = value
                    Me.RaisePropertyChanged("Pais")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CiudadServicio.ICiudadServicio")>  _
    Public Interface ICiudadServicio
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/DoWork", ReplyAction:="http://tempuri.org/ICiudadServicio/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/DoWork", ReplyAction:="http://tempuri.org/ICiudadServicio/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/Lista", ReplyAction:="http://tempuri.org/ICiudadServicio/ListaResponse")>  _
        Function Lista() As System.Collections.Generic.List(Of CiudadServicio.DCiudad)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/Lista", ReplyAction:="http://tempuri.org/ICiudadServicio/ListaResponse")>  _
        Function ListaAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CiudadServicio.DCiudad))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/Filtrar", ReplyAction:="http://tempuri.org/ICiudadServicio/FiltrarResponse")>  _
        Function Filtrar(ByVal Nombre As String) As System.Collections.Generic.List(Of CiudadServicio.DCiudad)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/Filtrar", ReplyAction:="http://tempuri.org/ICiudadServicio/FiltrarResponse")>  _
        Function FiltrarAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CiudadServicio.DCiudad))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/Guardar", ReplyAction:="http://tempuri.org/ICiudadServicio/GuardarResponse")>  _
        Sub Guardar(ByVal Carrera As CiudadServicio.DCiudad)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/Guardar", ReplyAction:="http://tempuri.org/ICiudadServicio/GuardarResponse")>  _
        Function GuardarAsync(ByVal Carrera As CiudadServicio.DCiudad) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/Editar", ReplyAction:="http://tempuri.org/ICiudadServicio/EditarResponse")>  _
        Sub Editar(ByVal Ciudad As CiudadServicio.DCiudad)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/Editar", ReplyAction:="http://tempuri.org/ICiudadServicio/EditarResponse")>  _
        Function EditarAsync(ByVal Ciudad As CiudadServicio.DCiudad) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/Eliminar", ReplyAction:="http://tempuri.org/ICiudadServicio/EliminarResponse")>  _
        Sub Eliminar(ByVal IdCiudad As System.Guid)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/Eliminar", ReplyAction:="http://tempuri.org/ICiudadServicio/EliminarResponse")>  _
        Function EliminarAsync(ByVal IdCiudad As System.Guid) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/BuscarPorNombre", ReplyAction:="http://tempuri.org/ICiudadServicio/BuscarPorNombreResponse")>  _
        Function BuscarPorNombre(ByVal Nombre As String) As CiudadServicio.DCiudad
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/BuscarPorNombre", ReplyAction:="http://tempuri.org/ICiudadServicio/BuscarPorNombreResponse")>  _
        Function BuscarPorNombreAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of CiudadServicio.DCiudad)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/BuscarPorId", ReplyAction:="http://tempuri.org/ICiudadServicio/BuscarPorIdResponse")>  _
        Function BuscarPorId(ByVal IdCarrera As System.Guid) As CiudadServicio.DCiudad
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICiudadServicio/BuscarPorId", ReplyAction:="http://tempuri.org/ICiudadServicio/BuscarPorIdResponse")>  _
        Function BuscarPorIdAsync(ByVal IdCarrera As System.Guid) As System.Threading.Tasks.Task(Of CiudadServicio.DCiudad)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICiudadServicioChannel
        Inherits CiudadServicio.ICiudadServicio, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CiudadServicioClient
        Inherits System.ServiceModel.ClientBase(Of CiudadServicio.ICiudadServicio)
        Implements CiudadServicio.ICiudadServicio
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements CiudadServicio.ICiudadServicio.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements CiudadServicio.ICiudadServicio.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
        
        Public Function Lista() As System.Collections.Generic.List(Of CiudadServicio.DCiudad) Implements CiudadServicio.ICiudadServicio.Lista
            Return MyBase.Channel.Lista
        End Function
        
        Public Function ListaAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CiudadServicio.DCiudad)) Implements CiudadServicio.ICiudadServicio.ListaAsync
            Return MyBase.Channel.ListaAsync
        End Function
        
        Public Function Filtrar(ByVal Nombre As String) As System.Collections.Generic.List(Of CiudadServicio.DCiudad) Implements CiudadServicio.ICiudadServicio.Filtrar
            Return MyBase.Channel.Filtrar(Nombre)
        End Function
        
        Public Function FiltrarAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CiudadServicio.DCiudad)) Implements CiudadServicio.ICiudadServicio.FiltrarAsync
            Return MyBase.Channel.FiltrarAsync(Nombre)
        End Function
        
        Public Sub Guardar(ByVal Carrera As CiudadServicio.DCiudad) Implements CiudadServicio.ICiudadServicio.Guardar
            MyBase.Channel.Guardar(Carrera)
        End Sub
        
        Public Function GuardarAsync(ByVal Carrera As CiudadServicio.DCiudad) As System.Threading.Tasks.Task Implements CiudadServicio.ICiudadServicio.GuardarAsync
            Return MyBase.Channel.GuardarAsync(Carrera)
        End Function
        
        Public Sub Editar(ByVal Ciudad As CiudadServicio.DCiudad) Implements CiudadServicio.ICiudadServicio.Editar
            MyBase.Channel.Editar(Ciudad)
        End Sub
        
        Public Function EditarAsync(ByVal Ciudad As CiudadServicio.DCiudad) As System.Threading.Tasks.Task Implements CiudadServicio.ICiudadServicio.EditarAsync
            Return MyBase.Channel.EditarAsync(Ciudad)
        End Function
        
        Public Sub Eliminar(ByVal IdCiudad As System.Guid) Implements CiudadServicio.ICiudadServicio.Eliminar
            MyBase.Channel.Eliminar(IdCiudad)
        End Sub
        
        Public Function EliminarAsync(ByVal IdCiudad As System.Guid) As System.Threading.Tasks.Task Implements CiudadServicio.ICiudadServicio.EliminarAsync
            Return MyBase.Channel.EliminarAsync(IdCiudad)
        End Function
        
        Public Function BuscarPorNombre(ByVal Nombre As String) As CiudadServicio.DCiudad Implements CiudadServicio.ICiudadServicio.BuscarPorNombre
            Return MyBase.Channel.BuscarPorNombre(Nombre)
        End Function
        
        Public Function BuscarPorNombreAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of CiudadServicio.DCiudad) Implements CiudadServicio.ICiudadServicio.BuscarPorNombreAsync
            Return MyBase.Channel.BuscarPorNombreAsync(Nombre)
        End Function
        
        Public Function BuscarPorId(ByVal IdCarrera As System.Guid) As CiudadServicio.DCiudad Implements CiudadServicio.ICiudadServicio.BuscarPorId
            Return MyBase.Channel.BuscarPorId(IdCarrera)
        End Function
        
        Public Function BuscarPorIdAsync(ByVal IdCarrera As System.Guid) As System.Threading.Tasks.Task(Of CiudadServicio.DCiudad) Implements CiudadServicio.ICiudadServicio.BuscarPorIdAsync
            Return MyBase.Channel.BuscarPorIdAsync(IdCarrera)
        End Function
    End Class
End Namespace
