'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace PrestamoServicio
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DPrestamo", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DPrestamo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AreaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CarreraField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartamentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartamentoAcademicoDocenteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartamentoAcademicoEstudianteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EdadField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaPrestamoField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdPersonaField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdPrestamoField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdentificacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MunicipioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NCarnetField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombrePersonaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObservacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SexoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoIdentificacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoPersonaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TurnoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As Boolean
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Area() As String
            Get
                Return Me.AreaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AreaField, value) <> true) Then
                    Me.AreaField = value
                    Me.RaisePropertyChanged("Area")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Carrera() As String
            Get
                Return Me.CarreraField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CarreraField, value) <> true) Then
                    Me.CarreraField = value
                    Me.RaisePropertyChanged("Carrera")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Departamento() As String
            Get
                Return Me.DepartamentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartamentoField, value) <> true) Then
                    Me.DepartamentoField = value
                    Me.RaisePropertyChanged("Departamento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DepartamentoAcademicoDocente() As String
            Get
                Return Me.DepartamentoAcademicoDocenteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartamentoAcademicoDocenteField, value) <> true) Then
                    Me.DepartamentoAcademicoDocenteField = value
                    Me.RaisePropertyChanged("DepartamentoAcademicoDocente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DepartamentoAcademicoEstudiante() As String
            Get
                Return Me.DepartamentoAcademicoEstudianteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartamentoAcademicoEstudianteField, value) <> true) Then
                    Me.DepartamentoAcademicoEstudianteField = value
                    Me.RaisePropertyChanged("DepartamentoAcademicoEstudiante")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Edad() As Integer
            Get
                Return Me.EdadField
            End Get
            Set
                If (Me.EdadField.Equals(value) <> true) Then
                    Me.EdadField = value
                    Me.RaisePropertyChanged("Edad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaPrestamo() As Date
            Get
                Return Me.FechaPrestamoField
            End Get
            Set
                If (Me.FechaPrestamoField.Equals(value) <> true) Then
                    Me.FechaPrestamoField = value
                    Me.RaisePropertyChanged("FechaPrestamo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdPersona() As System.Guid
            Get
                Return Me.IdPersonaField
            End Get
            Set
                If (Me.IdPersonaField.Equals(value) <> true) Then
                    Me.IdPersonaField = value
                    Me.RaisePropertyChanged("IdPersona")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdPrestamo() As System.Guid
            Get
                Return Me.IdPrestamoField
            End Get
            Set
                If (Me.IdPrestamoField.Equals(value) <> true) Then
                    Me.IdPrestamoField = value
                    Me.RaisePropertyChanged("IdPrestamo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Identificacion() As String
            Get
                Return Me.IdentificacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdentificacionField, value) <> true) Then
                    Me.IdentificacionField = value
                    Me.RaisePropertyChanged("Identificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Municipio() As String
            Get
                Return Me.MunicipioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MunicipioField, value) <> true) Then
                    Me.MunicipioField = value
                    Me.RaisePropertyChanged("Municipio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property N() As Long
            Get
                Return Me.NField
            End Get
            Set
                If (Me.NField.Equals(value) <> true) Then
                    Me.NField = value
                    Me.RaisePropertyChanged("N")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NCarnet() As String
            Get
                Return Me.NCarnetField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NCarnetField, value) <> true) Then
                    Me.NCarnetField = value
                    Me.RaisePropertyChanged("NCarnet")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombrePersona() As String
            Get
                Return Me.NombrePersonaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombrePersonaField, value) <> true) Then
                    Me.NombrePersonaField = value
                    Me.RaisePropertyChanged("NombrePersona")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Observacion() As String
            Get
                Return Me.ObservacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObservacionField, value) <> true) Then
                    Me.ObservacionField = value
                    Me.RaisePropertyChanged("Observacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sexo() As Boolean
            Get
                Return Me.SexoField
            End Get
            Set
                If (Me.SexoField.Equals(value) <> true) Then
                    Me.SexoField = value
                    Me.RaisePropertyChanged("Sexo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Tipo() As String
            Get
                Return Me.TipoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoField, value) <> true) Then
                    Me.TipoField = value
                    Me.RaisePropertyChanged("Tipo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoIdentificacion() As String
            Get
                Return Me.TipoIdentificacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoIdentificacionField, value) <> true) Then
                    Me.TipoIdentificacionField = value
                    Me.RaisePropertyChanged("TipoIdentificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoPersona() As String
            Get
                Return Me.TipoPersonaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoPersonaField, value) <> true) Then
                    Me.TipoPersonaField = value
                    Me.RaisePropertyChanged("TipoPersona")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Turno() As String
            Get
                Return Me.TurnoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TurnoField, value) <> true) Then
                    Me.TurnoField = value
                    Me.RaisePropertyChanged("Turno")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DInventario", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DInventario
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Autor1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Autor2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Autor3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EdicionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EditorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdAdquisicionField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdInventarioField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdLibroField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdiomaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InstitucionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsbnField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OtroTituloField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrestadoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RegistroField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SignaturaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoDocumentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoRegistroField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TituloField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As Boolean
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Autor1() As String
            Get
                Return Me.Autor1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Autor1Field, value) <> true) Then
                    Me.Autor1Field = value
                    Me.RaisePropertyChanged("Autor1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Autor2() As String
            Get
                Return Me.Autor2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Autor2Field, value) <> true) Then
                    Me.Autor2Field = value
                    Me.RaisePropertyChanged("Autor2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Autor3() As String
            Get
                Return Me.Autor3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Autor3Field, value) <> true) Then
                    Me.Autor3Field = value
                    Me.RaisePropertyChanged("Autor3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Edicion() As String
            Get
                Return Me.EdicionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EdicionField, value) <> true) Then
                    Me.EdicionField = value
                    Me.RaisePropertyChanged("Edicion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Editor() As String
            Get
                Return Me.EditorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EditorField, value) <> true) Then
                    Me.EditorField = value
                    Me.RaisePropertyChanged("Editor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdAdquisicion() As System.Guid
            Get
                Return Me.IdAdquisicionField
            End Get
            Set
                If (Me.IdAdquisicionField.Equals(value) <> true) Then
                    Me.IdAdquisicionField = value
                    Me.RaisePropertyChanged("IdAdquisicion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdInventario() As System.Guid
            Get
                Return Me.IdInventarioField
            End Get
            Set
                If (Me.IdInventarioField.Equals(value) <> true) Then
                    Me.IdInventarioField = value
                    Me.RaisePropertyChanged("IdInventario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdLibro() As System.Guid
            Get
                Return Me.IdLibroField
            End Get
            Set
                If (Me.IdLibroField.Equals(value) <> true) Then
                    Me.IdLibroField = value
                    Me.RaisePropertyChanged("IdLibro")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Idioma() As String
            Get
                Return Me.IdiomaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdiomaField, value) <> true) Then
                    Me.IdiomaField = value
                    Me.RaisePropertyChanged("Idioma")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Institucion() As String
            Get
                Return Me.InstitucionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InstitucionField, value) <> true) Then
                    Me.InstitucionField = value
                    Me.RaisePropertyChanged("Institucion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Isbn() As String
            Get
                Return Me.IsbnField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IsbnField, value) <> true) Then
                    Me.IsbnField = value
                    Me.RaisePropertyChanged("Isbn")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OtroTitulo() As String
            Get
                Return Me.OtroTituloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OtroTituloField, value) <> true) Then
                    Me.OtroTituloField = value
                    Me.RaisePropertyChanged("OtroTitulo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Prestado() As Boolean
            Get
                Return Me.PrestadoField
            End Get
            Set
                If (Me.PrestadoField.Equals(value) <> true) Then
                    Me.PrestadoField = value
                    Me.RaisePropertyChanged("Prestado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Registro() As String
            Get
                Return Me.RegistroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RegistroField, value) <> true) Then
                    Me.RegistroField = value
                    Me.RaisePropertyChanged("Registro")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Signatura() As String
            Get
                Return Me.SignaturaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SignaturaField, value) <> true) Then
                    Me.SignaturaField = value
                    Me.RaisePropertyChanged("Signatura")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoDocumento() As String
            Get
                Return Me.TipoDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoDocumentoField, value) <> true) Then
                    Me.TipoDocumentoField = value
                    Me.RaisePropertyChanged("TipoDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoRegistro() As String
            Get
                Return Me.TipoRegistroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoRegistroField, value) <> true) Then
                    Me.TipoRegistroField = value
                    Me.RaisePropertyChanged("TipoRegistro")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Titulo() As String
            Get
                Return Me.TituloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TituloField, value) <> true) Then
                    Me.TituloField = value
                    Me.RaisePropertyChanged("Titulo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DDetallePrestamo", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DDetallePrestamo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Autor1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Autor2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Autor3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EdicionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EditorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdDetallePrestamoField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdInventarioField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdPrestamoField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdiomaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InstitucionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsbnField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OtroTituloField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RegistroField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SignaturaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoDocumentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoRegistroField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TituloField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Autor1() As String
            Get
                Return Me.Autor1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Autor1Field, value) <> true) Then
                    Me.Autor1Field = value
                    Me.RaisePropertyChanged("Autor1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Autor2() As String
            Get
                Return Me.Autor2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Autor2Field, value) <> true) Then
                    Me.Autor2Field = value
                    Me.RaisePropertyChanged("Autor2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Autor3() As String
            Get
                Return Me.Autor3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Autor3Field, value) <> true) Then
                    Me.Autor3Field = value
                    Me.RaisePropertyChanged("Autor3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Edicion() As String
            Get
                Return Me.EdicionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EdicionField, value) <> true) Then
                    Me.EdicionField = value
                    Me.RaisePropertyChanged("Edicion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Editor() As String
            Get
                Return Me.EditorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EditorField, value) <> true) Then
                    Me.EditorField = value
                    Me.RaisePropertyChanged("Editor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdDetallePrestamo() As System.Guid
            Get
                Return Me.IdDetallePrestamoField
            End Get
            Set
                If (Me.IdDetallePrestamoField.Equals(value) <> true) Then
                    Me.IdDetallePrestamoField = value
                    Me.RaisePropertyChanged("IdDetallePrestamo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdInventario() As System.Guid
            Get
                Return Me.IdInventarioField
            End Get
            Set
                If (Me.IdInventarioField.Equals(value) <> true) Then
                    Me.IdInventarioField = value
                    Me.RaisePropertyChanged("IdInventario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdPrestamo() As System.Guid
            Get
                Return Me.IdPrestamoField
            End Get
            Set
                If (Me.IdPrestamoField.Equals(value) <> true) Then
                    Me.IdPrestamoField = value
                    Me.RaisePropertyChanged("IdPrestamo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Idioma() As String
            Get
                Return Me.IdiomaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdiomaField, value) <> true) Then
                    Me.IdiomaField = value
                    Me.RaisePropertyChanged("Idioma")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Institucion() As String
            Get
                Return Me.InstitucionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InstitucionField, value) <> true) Then
                    Me.InstitucionField = value
                    Me.RaisePropertyChanged("Institucion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Isbn() As String
            Get
                Return Me.IsbnField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IsbnField, value) <> true) Then
                    Me.IsbnField = value
                    Me.RaisePropertyChanged("Isbn")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OtroTitulo() As String
            Get
                Return Me.OtroTituloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OtroTituloField, value) <> true) Then
                    Me.OtroTituloField = value
                    Me.RaisePropertyChanged("OtroTitulo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Registro() As String
            Get
                Return Me.RegistroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RegistroField, value) <> true) Then
                    Me.RegistroField = value
                    Me.RaisePropertyChanged("Registro")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Signatura() As String
            Get
                Return Me.SignaturaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SignaturaField, value) <> true) Then
                    Me.SignaturaField = value
                    Me.RaisePropertyChanged("Signatura")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoDocumento() As String
            Get
                Return Me.TipoDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoDocumentoField, value) <> true) Then
                    Me.TipoDocumentoField = value
                    Me.RaisePropertyChanged("TipoDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoRegistro() As String
            Get
                Return Me.TipoRegistroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoRegistroField, value) <> true) Then
                    Me.TipoRegistroField = value
                    Me.RaisePropertyChanged("TipoRegistro")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Titulo() As String
            Get
                Return Me.TituloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TituloField, value) <> true) Then
                    Me.TituloField = value
                    Me.RaisePropertyChanged("Titulo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="PrestamoServicio.IPrestamoServicio")>  _
    Public Interface IPrestamoServicio
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/DoWork", ReplyAction:="http://tempuri.org/IPrestamoServicio/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/DoWork", ReplyAction:="http://tempuri.org/IPrestamoServicio/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/Guardar", ReplyAction:="http://tempuri.org/IPrestamoServicio/GuardarResponse")>  _
        Sub Guardar(ByVal Prestamo As PrestamoServicio.DPrestamo, ByVal BibliografiaPrestar As System.Collections.Generic.List(Of PrestamoServicio.DInventario))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/Guardar", ReplyAction:="http://tempuri.org/IPrestamoServicio/GuardarResponse")>  _
        Function GuardarAsync(ByVal Prestamo As PrestamoServicio.DPrestamo, ByVal BibliografiaPrestar As System.Collections.Generic.List(Of PrestamoServicio.DInventario)) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/Editar", ReplyAction:="http://tempuri.org/IPrestamoServicio/EditarResponse")>  _
        Sub Editar(ByVal Prestamo As PrestamoServicio.DPrestamo, ByVal BibliografiaPrestar As System.Collections.Generic.List(Of PrestamoServicio.DInventario))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/Editar", ReplyAction:="http://tempuri.org/IPrestamoServicio/EditarResponse")>  _
        Function EditarAsync(ByVal Prestamo As PrestamoServicio.DPrestamo, ByVal BibliografiaPrestar As System.Collections.Generic.List(Of PrestamoServicio.DInventario)) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/Eliminar", ReplyAction:="http://tempuri.org/IPrestamoServicio/EliminarResponse")>  _
        Sub Eliminar(ByVal IdPrestamo As System.Guid)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/Eliminar", ReplyAction:="http://tempuri.org/IPrestamoServicio/EliminarResponse")>  _
        Function EliminarAsync(ByVal IdPrestamo As System.Guid) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/Lista", ReplyAction:="http://tempuri.org/IPrestamoServicio/ListaResponse")>  _
        Function Lista(ByVal Prestamo As PrestamoServicio.DPrestamo, ByVal Inicio As Date, ByVal Final As Date, ByVal EdadMinima As Integer, ByVal EdadMaxima As Integer) As System.Collections.Generic.List(Of PrestamoServicio.DPrestamo)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/Lista", ReplyAction:="http://tempuri.org/IPrestamoServicio/ListaResponse")>  _
        Function ListaAsync(ByVal Prestamo As PrestamoServicio.DPrestamo, ByVal Inicio As Date, ByVal Final As Date, ByVal EdadMinima As Integer, ByVal EdadMaxima As Integer) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PrestamoServicio.DPrestamo))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/BuscarPorId", ReplyAction:="http://tempuri.org/IPrestamoServicio/BuscarPorIdResponse")>  _
        Function BuscarPorId(ByVal IdPrestamo As System.Guid) As PrestamoServicio.DPrestamo
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/BuscarPorId", ReplyAction:="http://tempuri.org/IPrestamoServicio/BuscarPorIdResponse")>  _
        Function BuscarPorIdAsync(ByVal IdPrestamo As System.Guid) As System.Threading.Tasks.Task(Of PrestamoServicio.DPrestamo)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/BuscarPorN", ReplyAction:="http://tempuri.org/IPrestamoServicio/BuscarPorNResponse")>  _
        Function BuscarPorN(ByVal N As Integer) As PrestamoServicio.DPrestamo
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/BuscarPorN", ReplyAction:="http://tempuri.org/IPrestamoServicio/BuscarPorNResponse")>  _
        Function BuscarPorNAsync(ByVal N As Integer) As System.Threading.Tasks.Task(Of PrestamoServicio.DPrestamo)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/ListadoDetalle", ReplyAction:="http://tempuri.org/IPrestamoServicio/ListadoDetalleResponse")>  _
        Function ListadoDetalle(ByVal IdPrestamo As System.Guid) As System.Collections.Generic.List(Of PrestamoServicio.DDetallePrestamo)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/ListadoDetalle", ReplyAction:="http://tempuri.org/IPrestamoServicio/ListadoDetalleResponse")>  _
        Function ListadoDetalleAsync(ByVal IdPrestamo As System.Guid) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PrestamoServicio.DDetallePrestamo))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/BuscarPorRegistro", ReplyAction:="http://tempuri.org/IPrestamoServicio/BuscarPorRegistroResponse")>  _
        Function BuscarPorRegistro(ByVal Registro As String) As PrestamoServicio.DInventario
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/BuscarPorRegistro", ReplyAction:="http://tempuri.org/IPrestamoServicio/BuscarPorRegistroResponse")>  _
        Function BuscarPorRegistroAsync(ByVal Registro As String) As System.Threading.Tasks.Task(Of PrestamoServicio.DInventario)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/Busqueda", ReplyAction:="http://tempuri.org/IPrestamoServicio/BusquedaResponse")>  _
        Function Busqueda(ByVal Inicio As Date, ByVal Final As Date, ByVal Persona As String) As System.Collections.Generic.List(Of PrestamoServicio.DPrestamo)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/Busqueda", ReplyAction:="http://tempuri.org/IPrestamoServicio/BusquedaResponse")>  _
        Function BusquedaAsync(ByVal Inicio As Date, ByVal Final As Date, ByVal Persona As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PrestamoServicio.DPrestamo))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/Entregar", ReplyAction:="http://tempuri.org/IPrestamoServicio/EntregarResponse")>  _
        Sub Entregar(ByVal IdInventario As System.Guid)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/Entregar", ReplyAction:="http://tempuri.org/IPrestamoServicio/EntregarResponse")>  _
        Function EntregarAsync(ByVal IdInventario As System.Guid) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/Solvencia", ReplyAction:="http://tempuri.org/IPrestamoServicio/SolvenciaResponse")>  _
        Function Solvencia() As System.Collections.Generic.List(Of PrestamoServicio.DInventario)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPrestamoServicio/Solvencia", ReplyAction:="http://tempuri.org/IPrestamoServicio/SolvenciaResponse")>  _
        Function SolvenciaAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PrestamoServicio.DInventario))
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IPrestamoServicioChannel
        Inherits PrestamoServicio.IPrestamoServicio, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PrestamoServicioClient
        Inherits System.ServiceModel.ClientBase(Of PrestamoServicio.IPrestamoServicio)
        Implements PrestamoServicio.IPrestamoServicio
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements PrestamoServicio.IPrestamoServicio.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements PrestamoServicio.IPrestamoServicio.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
        
        Public Sub Guardar(ByVal Prestamo As PrestamoServicio.DPrestamo, ByVal BibliografiaPrestar As System.Collections.Generic.List(Of PrestamoServicio.DInventario)) Implements PrestamoServicio.IPrestamoServicio.Guardar
            MyBase.Channel.Guardar(Prestamo, BibliografiaPrestar)
        End Sub
        
        Public Function GuardarAsync(ByVal Prestamo As PrestamoServicio.DPrestamo, ByVal BibliografiaPrestar As System.Collections.Generic.List(Of PrestamoServicio.DInventario)) As System.Threading.Tasks.Task Implements PrestamoServicio.IPrestamoServicio.GuardarAsync
            Return MyBase.Channel.GuardarAsync(Prestamo, BibliografiaPrestar)
        End Function
        
        Public Sub Editar(ByVal Prestamo As PrestamoServicio.DPrestamo, ByVal BibliografiaPrestar As System.Collections.Generic.List(Of PrestamoServicio.DInventario)) Implements PrestamoServicio.IPrestamoServicio.Editar
            MyBase.Channel.Editar(Prestamo, BibliografiaPrestar)
        End Sub
        
        Public Function EditarAsync(ByVal Prestamo As PrestamoServicio.DPrestamo, ByVal BibliografiaPrestar As System.Collections.Generic.List(Of PrestamoServicio.DInventario)) As System.Threading.Tasks.Task Implements PrestamoServicio.IPrestamoServicio.EditarAsync
            Return MyBase.Channel.EditarAsync(Prestamo, BibliografiaPrestar)
        End Function
        
        Public Sub Eliminar(ByVal IdPrestamo As System.Guid) Implements PrestamoServicio.IPrestamoServicio.Eliminar
            MyBase.Channel.Eliminar(IdPrestamo)
        End Sub
        
        Public Function EliminarAsync(ByVal IdPrestamo As System.Guid) As System.Threading.Tasks.Task Implements PrestamoServicio.IPrestamoServicio.EliminarAsync
            Return MyBase.Channel.EliminarAsync(IdPrestamo)
        End Function
        
        Public Function Lista(ByVal Prestamo As PrestamoServicio.DPrestamo, ByVal Inicio As Date, ByVal Final As Date, ByVal EdadMinima As Integer, ByVal EdadMaxima As Integer) As System.Collections.Generic.List(Of PrestamoServicio.DPrestamo) Implements PrestamoServicio.IPrestamoServicio.Lista
            Return MyBase.Channel.Lista(Prestamo, Inicio, Final, EdadMinima, EdadMaxima)
        End Function
        
        Public Function ListaAsync(ByVal Prestamo As PrestamoServicio.DPrestamo, ByVal Inicio As Date, ByVal Final As Date, ByVal EdadMinima As Integer, ByVal EdadMaxima As Integer) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PrestamoServicio.DPrestamo)) Implements PrestamoServicio.IPrestamoServicio.ListaAsync
            Return MyBase.Channel.ListaAsync(Prestamo, Inicio, Final, EdadMinima, EdadMaxima)
        End Function
        
        Public Function BuscarPorId(ByVal IdPrestamo As System.Guid) As PrestamoServicio.DPrestamo Implements PrestamoServicio.IPrestamoServicio.BuscarPorId
            Return MyBase.Channel.BuscarPorId(IdPrestamo)
        End Function
        
        Public Function BuscarPorIdAsync(ByVal IdPrestamo As System.Guid) As System.Threading.Tasks.Task(Of PrestamoServicio.DPrestamo) Implements PrestamoServicio.IPrestamoServicio.BuscarPorIdAsync
            Return MyBase.Channel.BuscarPorIdAsync(IdPrestamo)
        End Function
        
        Public Function BuscarPorN(ByVal N As Integer) As PrestamoServicio.DPrestamo Implements PrestamoServicio.IPrestamoServicio.BuscarPorN
            Return MyBase.Channel.BuscarPorN(N)
        End Function
        
        Public Function BuscarPorNAsync(ByVal N As Integer) As System.Threading.Tasks.Task(Of PrestamoServicio.DPrestamo) Implements PrestamoServicio.IPrestamoServicio.BuscarPorNAsync
            Return MyBase.Channel.BuscarPorNAsync(N)
        End Function
        
        Public Function ListadoDetalle(ByVal IdPrestamo As System.Guid) As System.Collections.Generic.List(Of PrestamoServicio.DDetallePrestamo) Implements PrestamoServicio.IPrestamoServicio.ListadoDetalle
            Return MyBase.Channel.ListadoDetalle(IdPrestamo)
        End Function
        
        Public Function ListadoDetalleAsync(ByVal IdPrestamo As System.Guid) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PrestamoServicio.DDetallePrestamo)) Implements PrestamoServicio.IPrestamoServicio.ListadoDetalleAsync
            Return MyBase.Channel.ListadoDetalleAsync(IdPrestamo)
        End Function
        
        Public Function BuscarPorRegistro(ByVal Registro As String) As PrestamoServicio.DInventario Implements PrestamoServicio.IPrestamoServicio.BuscarPorRegistro
            Return MyBase.Channel.BuscarPorRegistro(Registro)
        End Function
        
        Public Function BuscarPorRegistroAsync(ByVal Registro As String) As System.Threading.Tasks.Task(Of PrestamoServicio.DInventario) Implements PrestamoServicio.IPrestamoServicio.BuscarPorRegistroAsync
            Return MyBase.Channel.BuscarPorRegistroAsync(Registro)
        End Function
        
        Public Function Busqueda(ByVal Inicio As Date, ByVal Final As Date, ByVal Persona As String) As System.Collections.Generic.List(Of PrestamoServicio.DPrestamo) Implements PrestamoServicio.IPrestamoServicio.Busqueda
            Return MyBase.Channel.Busqueda(Inicio, Final, Persona)
        End Function
        
        Public Function BusquedaAsync(ByVal Inicio As Date, ByVal Final As Date, ByVal Persona As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PrestamoServicio.DPrestamo)) Implements PrestamoServicio.IPrestamoServicio.BusquedaAsync
            Return MyBase.Channel.BusquedaAsync(Inicio, Final, Persona)
        End Function
        
        Public Sub Entregar(ByVal IdInventario As System.Guid) Implements PrestamoServicio.IPrestamoServicio.Entregar
            MyBase.Channel.Entregar(IdInventario)
        End Sub
        
        Public Function EntregarAsync(ByVal IdInventario As System.Guid) As System.Threading.Tasks.Task Implements PrestamoServicio.IPrestamoServicio.EntregarAsync
            Return MyBase.Channel.EntregarAsync(IdInventario)
        End Function
        
        Public Function Solvencia() As System.Collections.Generic.List(Of PrestamoServicio.DInventario) Implements PrestamoServicio.IPrestamoServicio.Solvencia
            Return MyBase.Channel.Solvencia
        End Function
        
        Public Function SolvenciaAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PrestamoServicio.DInventario)) Implements PrestamoServicio.IPrestamoServicio.SolvenciaAsync
            Return MyBase.Channel.SolvenciaAsync
        End Function
    End Class
End Namespace
