'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace GradoServicio
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DGrado", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DGrado
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdGradoField As System.Guid
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Descripcion() As String
            Get
                Return Me.DescripcionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionField, value) <> true) Then
                    Me.DescripcionField = value
                    Me.RaisePropertyChanged("Descripcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdGrado() As System.Guid
            Get
                Return Me.IdGradoField
            End Get
            Set
                If (Me.IdGradoField.Equals(value) <> true) Then
                    Me.IdGradoField = value
                    Me.RaisePropertyChanged("IdGrado")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="GradoServicio.IGradoServicio")>  _
    Public Interface IGradoServicio
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGradoServicio/DoWork", ReplyAction:="http://tempuri.org/IGradoServicio/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGradoServicio/DoWork", ReplyAction:="http://tempuri.org/IGradoServicio/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGradoServicio/Guardar", ReplyAction:="http://tempuri.org/IGradoServicio/GuardarResponse")>  _
        Sub Guardar(ByVal Grado As GradoServicio.DGrado)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGradoServicio/Guardar", ReplyAction:="http://tempuri.org/IGradoServicio/GuardarResponse")>  _
        Function GuardarAsync(ByVal Grado As GradoServicio.DGrado) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGradoServicio/Lista", ReplyAction:="http://tempuri.org/IGradoServicio/ListaResponse")>  _
        Function Lista() As System.Collections.Generic.List(Of GradoServicio.DGrado)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGradoServicio/Lista", ReplyAction:="http://tempuri.org/IGradoServicio/ListaResponse")>  _
        Function ListaAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of GradoServicio.DGrado))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGradoServicio/BuscarPorDescripcion", ReplyAction:="http://tempuri.org/IGradoServicio/BuscarPorDescripcionResponse")>  _
        Function BuscarPorDescripcion(ByVal Descripcion As String) As GradoServicio.DGrado
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGradoServicio/BuscarPorDescripcion", ReplyAction:="http://tempuri.org/IGradoServicio/BuscarPorDescripcionResponse")>  _
        Function BuscarPorDescripcionAsync(ByVal Descripcion As String) As System.Threading.Tasks.Task(Of GradoServicio.DGrado)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGradoServicio/Existe", ReplyAction:="http://tempuri.org/IGradoServicio/ExisteResponse")>  _
        Function Existe(ByVal Descripcion As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IGradoServicio/Existe", ReplyAction:="http://tempuri.org/IGradoServicio/ExisteResponse")>  _
        Function ExisteAsync(ByVal Descripcion As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IGradoServicioChannel
        Inherits GradoServicio.IGradoServicio, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class GradoServicioClient
        Inherits System.ServiceModel.ClientBase(Of GradoServicio.IGradoServicio)
        Implements GradoServicio.IGradoServicio
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements GradoServicio.IGradoServicio.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements GradoServicio.IGradoServicio.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
        
        Public Sub Guardar(ByVal Grado As GradoServicio.DGrado) Implements GradoServicio.IGradoServicio.Guardar
            MyBase.Channel.Guardar(Grado)
        End Sub
        
        Public Function GuardarAsync(ByVal Grado As GradoServicio.DGrado) As System.Threading.Tasks.Task Implements GradoServicio.IGradoServicio.GuardarAsync
            Return MyBase.Channel.GuardarAsync(Grado)
        End Function
        
        Public Function Lista() As System.Collections.Generic.List(Of GradoServicio.DGrado) Implements GradoServicio.IGradoServicio.Lista
            Return MyBase.Channel.Lista
        End Function
        
        Public Function ListaAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of GradoServicio.DGrado)) Implements GradoServicio.IGradoServicio.ListaAsync
            Return MyBase.Channel.ListaAsync
        End Function
        
        Public Function BuscarPorDescripcion(ByVal Descripcion As String) As GradoServicio.DGrado Implements GradoServicio.IGradoServicio.BuscarPorDescripcion
            Return MyBase.Channel.BuscarPorDescripcion(Descripcion)
        End Function
        
        Public Function BuscarPorDescripcionAsync(ByVal Descripcion As String) As System.Threading.Tasks.Task(Of GradoServicio.DGrado) Implements GradoServicio.IGradoServicio.BuscarPorDescripcionAsync
            Return MyBase.Channel.BuscarPorDescripcionAsync(Descripcion)
        End Function
        
        Public Function Existe(ByVal Descripcion As String) As Boolean Implements GradoServicio.IGradoServicio.Existe
            Return MyBase.Channel.Existe(Descripcion)
        End Function
        
        Public Function ExisteAsync(ByVal Descripcion As String) As System.Threading.Tasks.Task(Of Boolean) Implements GradoServicio.IGradoServicio.ExisteAsync
            Return MyBase.Channel.ExisteAsync(Descripcion)
        End Function
    End Class
End Namespace
