'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace InformePrestamoServicio
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DCantidadMensual3Columnas", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DCantidadMensual3Columnas
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private C1Field As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private C2Field As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private C3Field As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MesField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property C1() As Decimal
            Get
                Return Me.C1Field
            End Get
            Set
                If (Me.C1Field.Equals(value) <> true) Then
                    Me.C1Field = value
                    Me.RaisePropertyChanged("C1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property C2() As Decimal
            Get
                Return Me.C2Field
            End Get
            Set
                If (Me.C2Field.Equals(value) <> true) Then
                    Me.C2Field = value
                    Me.RaisePropertyChanged("C2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property C3() As Decimal
            Get
                Return Me.C3Field
            End Get
            Set
                If (Me.C3Field.Equals(value) <> true) Then
                    Me.C3Field = value
                    Me.RaisePropertyChanged("C3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Mes() As String
            Get
                Return Me.MesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MesField, value) <> true) Then
                    Me.MesField = value
                    Me.RaisePropertyChanged("Mes")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="InformePrestamoServicio.IInformePrestamoServicio")>  _
    Public Interface IInformePrestamoServicio
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInformePrestamoServicio/DoWork", ReplyAction:="http://tempuri.org/IInformePrestamoServicio/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInformePrestamoServicio/DoWork", ReplyAction:="http://tempuri.org/IInformePrestamoServicio/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInformePrestamoServicio/PrestamosPorDepartamento", ReplyAction:="http://tempuri.org/IInformePrestamoServicio/PrestamosPorDepartamentoResponse")>  _
        Function PrestamosPorDepartamento(ByVal Anual As Short, ByVal Modalidad As Byte, ByVal Departamento As Byte) As System.Collections.Generic.List(Of InformePrestamoServicio.DCantidadMensual3Columnas)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInformePrestamoServicio/PrestamosPorDepartamento", ReplyAction:="http://tempuri.org/IInformePrestamoServicio/PrestamosPorDepartamentoResponse")>  _
        Function PrestamosPorDepartamentoAsync(ByVal Anual As Short, ByVal Modalidad As Byte, ByVal Departamento As Byte) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of InformePrestamoServicio.DCantidadMensual3Columnas))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInformePrestamoServicio/PrestamosPorCarrera", ReplyAction:="http://tempuri.org/IInformePrestamoServicio/PrestamosPorCarreraResponse")>  _
        Function PrestamosPorCarrera(ByVal Anual As Short, ByVal Modalidad As Byte, ByVal Carrera As System.Guid) As System.Collections.Generic.List(Of InformePrestamoServicio.DCantidadMensual3Columnas)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInformePrestamoServicio/PrestamosPorCarrera", ReplyAction:="http://tempuri.org/IInformePrestamoServicio/PrestamosPorCarreraResponse")>  _
        Function PrestamosPorCarreraAsync(ByVal Anual As Short, ByVal Modalidad As Byte, ByVal Carrera As System.Guid) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of InformePrestamoServicio.DCantidadMensual3Columnas))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInformePrestamoServicio/PrestamosPorTipoPersona", ReplyAction:="http://tempuri.org/IInformePrestamoServicio/PrestamosPorTipoPersonaResponse")>  _
        Function PrestamosPorTipoPersona(ByVal Anual As Short, ByVal Modalidad As Byte, ByVal TipoPersona As Byte) As System.Collections.Generic.List(Of InformePrestamoServicio.DCantidadMensual3Columnas)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInformePrestamoServicio/PrestamosPorTipoPersona", ReplyAction:="http://tempuri.org/IInformePrestamoServicio/PrestamosPorTipoPersonaResponse")>  _
        Function PrestamosPorTipoPersonaAsync(ByVal Anual As Short, ByVal Modalidad As Byte, ByVal TipoPersona As Byte) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of InformePrestamoServicio.DCantidadMensual3Columnas))
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IInformePrestamoServicioChannel
        Inherits InformePrestamoServicio.IInformePrestamoServicio, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class InformePrestamoServicioClient
        Inherits System.ServiceModel.ClientBase(Of InformePrestamoServicio.IInformePrestamoServicio)
        Implements InformePrestamoServicio.IInformePrestamoServicio
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements InformePrestamoServicio.IInformePrestamoServicio.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements InformePrestamoServicio.IInformePrestamoServicio.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
        
        Public Function PrestamosPorDepartamento(ByVal Anual As Short, ByVal Modalidad As Byte, ByVal Departamento As Byte) As System.Collections.Generic.List(Of InformePrestamoServicio.DCantidadMensual3Columnas) Implements InformePrestamoServicio.IInformePrestamoServicio.PrestamosPorDepartamento
            Return MyBase.Channel.PrestamosPorDepartamento(Anual, Modalidad, Departamento)
        End Function
        
        Public Function PrestamosPorDepartamentoAsync(ByVal Anual As Short, ByVal Modalidad As Byte, ByVal Departamento As Byte) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of InformePrestamoServicio.DCantidadMensual3Columnas)) Implements InformePrestamoServicio.IInformePrestamoServicio.PrestamosPorDepartamentoAsync
            Return MyBase.Channel.PrestamosPorDepartamentoAsync(Anual, Modalidad, Departamento)
        End Function
        
        Public Function PrestamosPorCarrera(ByVal Anual As Short, ByVal Modalidad As Byte, ByVal Carrera As System.Guid) As System.Collections.Generic.List(Of InformePrestamoServicio.DCantidadMensual3Columnas) Implements InformePrestamoServicio.IInformePrestamoServicio.PrestamosPorCarrera
            Return MyBase.Channel.PrestamosPorCarrera(Anual, Modalidad, Carrera)
        End Function
        
        Public Function PrestamosPorCarreraAsync(ByVal Anual As Short, ByVal Modalidad As Byte, ByVal Carrera As System.Guid) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of InformePrestamoServicio.DCantidadMensual3Columnas)) Implements InformePrestamoServicio.IInformePrestamoServicio.PrestamosPorCarreraAsync
            Return MyBase.Channel.PrestamosPorCarreraAsync(Anual, Modalidad, Carrera)
        End Function
        
        Public Function PrestamosPorTipoPersona(ByVal Anual As Short, ByVal Modalidad As Byte, ByVal TipoPersona As Byte) As System.Collections.Generic.List(Of InformePrestamoServicio.DCantidadMensual3Columnas) Implements InformePrestamoServicio.IInformePrestamoServicio.PrestamosPorTipoPersona
            Return MyBase.Channel.PrestamosPorTipoPersona(Anual, Modalidad, TipoPersona)
        End Function
        
        Public Function PrestamosPorTipoPersonaAsync(ByVal Anual As Short, ByVal Modalidad As Byte, ByVal TipoPersona As Byte) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of InformePrestamoServicio.DCantidadMensual3Columnas)) Implements InformePrestamoServicio.IInformePrestamoServicio.PrestamosPorTipoPersonaAsync
            Return MyBase.Channel.PrestamosPorTipoPersonaAsync(Anual, Modalidad, TipoPersona)
        End Function
    End Class
End Namespace
