'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace PaisServicio
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DPais", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DPais
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodPaisField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdPaisField As System.Guid
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodPais() As String
            Get
                Return Me.CodPaisField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodPaisField, value) <> true) Then
                    Me.CodPaisField = value
                    Me.RaisePropertyChanged("CodPais")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Descripcion() As String
            Get
                Return Me.DescripcionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionField, value) <> true) Then
                    Me.DescripcionField = value
                    Me.RaisePropertyChanged("Descripcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdPais() As System.Guid
            Get
                Return Me.IdPaisField
            End Get
            Set
                If (Me.IdPaisField.Equals(value) <> true) Then
                    Me.IdPaisField = value
                    Me.RaisePropertyChanged("IdPais")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="PaisServicio.IPaisServicio")>  _
    Public Interface IPaisServicio
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/DoWork", ReplyAction:="http://tempuri.org/IPaisServicio/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/DoWork", ReplyAction:="http://tempuri.org/IPaisServicio/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/Lista", ReplyAction:="http://tempuri.org/IPaisServicio/ListaResponse")>  _
        Function Lista() As System.Collections.Generic.List(Of PaisServicio.DPais)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/Lista", ReplyAction:="http://tempuri.org/IPaisServicio/ListaResponse")>  _
        Function ListaAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PaisServicio.DPais))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/Filtrar", ReplyAction:="http://tempuri.org/IPaisServicio/FiltrarResponse")>  _
        Function Filtrar(ByVal Nombre As String) As System.Collections.Generic.List(Of PaisServicio.DPais)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/Filtrar", ReplyAction:="http://tempuri.org/IPaisServicio/FiltrarResponse")>  _
        Function FiltrarAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PaisServicio.DPais))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/Guardar", ReplyAction:="http://tempuri.org/IPaisServicio/GuardarResponse")>  _
        Sub Guardar(ByVal Pais As PaisServicio.DPais)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/Guardar", ReplyAction:="http://tempuri.org/IPaisServicio/GuardarResponse")>  _
        Function GuardarAsync(ByVal Pais As PaisServicio.DPais) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/Editar", ReplyAction:="http://tempuri.org/IPaisServicio/EditarResponse")>  _
        Sub Editar(ByVal Pais As PaisServicio.DPais)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/Editar", ReplyAction:="http://tempuri.org/IPaisServicio/EditarResponse")>  _
        Function EditarAsync(ByVal Pais As PaisServicio.DPais) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/Eliminar", ReplyAction:="http://tempuri.org/IPaisServicio/EliminarResponse")>  _
        Sub Eliminar(ByVal IdPais As System.Guid)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/Eliminar", ReplyAction:="http://tempuri.org/IPaisServicio/EliminarResponse")>  _
        Function EliminarAsync(ByVal IdPais As System.Guid) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/BuscarPorNombre", ReplyAction:="http://tempuri.org/IPaisServicio/BuscarPorNombreResponse")>  _
        Function BuscarPorNombre(ByVal Nombre As String) As PaisServicio.DPais
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/BuscarPorNombre", ReplyAction:="http://tempuri.org/IPaisServicio/BuscarPorNombreResponse")>  _
        Function BuscarPorNombreAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of PaisServicio.DPais)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/BuscarPorId", ReplyAction:="http://tempuri.org/IPaisServicio/BuscarPorIdResponse")>  _
        Function BuscarPorId(ByVal IdPais As System.Guid) As PaisServicio.DPais
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPaisServicio/BuscarPorId", ReplyAction:="http://tempuri.org/IPaisServicio/BuscarPorIdResponse")>  _
        Function BuscarPorIdAsync(ByVal IdPais As System.Guid) As System.Threading.Tasks.Task(Of PaisServicio.DPais)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IPaisServicioChannel
        Inherits PaisServicio.IPaisServicio, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PaisServicioClient
        Inherits System.ServiceModel.ClientBase(Of PaisServicio.IPaisServicio)
        Implements PaisServicio.IPaisServicio
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements PaisServicio.IPaisServicio.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements PaisServicio.IPaisServicio.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
        
        Public Function Lista() As System.Collections.Generic.List(Of PaisServicio.DPais) Implements PaisServicio.IPaisServicio.Lista
            Return MyBase.Channel.Lista
        End Function
        
        Public Function ListaAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PaisServicio.DPais)) Implements PaisServicio.IPaisServicio.ListaAsync
            Return MyBase.Channel.ListaAsync
        End Function
        
        Public Function Filtrar(ByVal Nombre As String) As System.Collections.Generic.List(Of PaisServicio.DPais) Implements PaisServicio.IPaisServicio.Filtrar
            Return MyBase.Channel.Filtrar(Nombre)
        End Function
        
        Public Function FiltrarAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PaisServicio.DPais)) Implements PaisServicio.IPaisServicio.FiltrarAsync
            Return MyBase.Channel.FiltrarAsync(Nombre)
        End Function
        
        Public Sub Guardar(ByVal Pais As PaisServicio.DPais) Implements PaisServicio.IPaisServicio.Guardar
            MyBase.Channel.Guardar(Pais)
        End Sub
        
        Public Function GuardarAsync(ByVal Pais As PaisServicio.DPais) As System.Threading.Tasks.Task Implements PaisServicio.IPaisServicio.GuardarAsync
            Return MyBase.Channel.GuardarAsync(Pais)
        End Function
        
        Public Sub Editar(ByVal Pais As PaisServicio.DPais) Implements PaisServicio.IPaisServicio.Editar
            MyBase.Channel.Editar(Pais)
        End Sub
        
        Public Function EditarAsync(ByVal Pais As PaisServicio.DPais) As System.Threading.Tasks.Task Implements PaisServicio.IPaisServicio.EditarAsync
            Return MyBase.Channel.EditarAsync(Pais)
        End Function
        
        Public Sub Eliminar(ByVal IdPais As System.Guid) Implements PaisServicio.IPaisServicio.Eliminar
            MyBase.Channel.Eliminar(IdPais)
        End Sub
        
        Public Function EliminarAsync(ByVal IdPais As System.Guid) As System.Threading.Tasks.Task Implements PaisServicio.IPaisServicio.EliminarAsync
            Return MyBase.Channel.EliminarAsync(IdPais)
        End Function
        
        Public Function BuscarPorNombre(ByVal Nombre As String) As PaisServicio.DPais Implements PaisServicio.IPaisServicio.BuscarPorNombre
            Return MyBase.Channel.BuscarPorNombre(Nombre)
        End Function
        
        Public Function BuscarPorNombreAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of PaisServicio.DPais) Implements PaisServicio.IPaisServicio.BuscarPorNombreAsync
            Return MyBase.Channel.BuscarPorNombreAsync(Nombre)
        End Function
        
        Public Function BuscarPorId(ByVal IdPais As System.Guid) As PaisServicio.DPais Implements PaisServicio.IPaisServicio.BuscarPorId
            Return MyBase.Channel.BuscarPorId(IdPais)
        End Function
        
        Public Function BuscarPorIdAsync(ByVal IdPais As System.Guid) As System.Threading.Tasks.Task(Of PaisServicio.DPais) Implements PaisServicio.IPaisServicio.BuscarPorIdAsync
            Return MyBase.Channel.BuscarPorIdAsync(IdPais)
        End Function
    End Class
End Namespace
