'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace InventarioServicio
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DInventario", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DInventario
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Autor1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Autor2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private Autor3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EdicionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EditorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdAdquisicionField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdInventarioField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdLibroField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdiomaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private InstitucionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsbnField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OtroTituloField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PrestadoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RegistroField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SignaturaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoDocumentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoRegistroField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TituloField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As Boolean
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Autor1() As String
            Get
                Return Me.Autor1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Autor1Field, value) <> true) Then
                    Me.Autor1Field = value
                    Me.RaisePropertyChanged("Autor1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Autor2() As String
            Get
                Return Me.Autor2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Autor2Field, value) <> true) Then
                    Me.Autor2Field = value
                    Me.RaisePropertyChanged("Autor2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Autor3() As String
            Get
                Return Me.Autor3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.Autor3Field, value) <> true) Then
                    Me.Autor3Field = value
                    Me.RaisePropertyChanged("Autor3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Edicion() As String
            Get
                Return Me.EdicionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EdicionField, value) <> true) Then
                    Me.EdicionField = value
                    Me.RaisePropertyChanged("Edicion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Editor() As String
            Get
                Return Me.EditorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EditorField, value) <> true) Then
                    Me.EditorField = value
                    Me.RaisePropertyChanged("Editor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdAdquisicion() As System.Guid
            Get
                Return Me.IdAdquisicionField
            End Get
            Set
                If (Me.IdAdquisicionField.Equals(value) <> true) Then
                    Me.IdAdquisicionField = value
                    Me.RaisePropertyChanged("IdAdquisicion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdInventario() As System.Guid
            Get
                Return Me.IdInventarioField
            End Get
            Set
                If (Me.IdInventarioField.Equals(value) <> true) Then
                    Me.IdInventarioField = value
                    Me.RaisePropertyChanged("IdInventario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdLibro() As System.Guid
            Get
                Return Me.IdLibroField
            End Get
            Set
                If (Me.IdLibroField.Equals(value) <> true) Then
                    Me.IdLibroField = value
                    Me.RaisePropertyChanged("IdLibro")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Idioma() As String
            Get
                Return Me.IdiomaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdiomaField, value) <> true) Then
                    Me.IdiomaField = value
                    Me.RaisePropertyChanged("Idioma")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Institucion() As String
            Get
                Return Me.InstitucionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.InstitucionField, value) <> true) Then
                    Me.InstitucionField = value
                    Me.RaisePropertyChanged("Institucion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Isbn() As String
            Get
                Return Me.IsbnField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IsbnField, value) <> true) Then
                    Me.IsbnField = value
                    Me.RaisePropertyChanged("Isbn")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OtroTitulo() As String
            Get
                Return Me.OtroTituloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OtroTituloField, value) <> true) Then
                    Me.OtroTituloField = value
                    Me.RaisePropertyChanged("OtroTitulo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Prestado() As Boolean
            Get
                Return Me.PrestadoField
            End Get
            Set
                If (Me.PrestadoField.Equals(value) <> true) Then
                    Me.PrestadoField = value
                    Me.RaisePropertyChanged("Prestado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Registro() As String
            Get
                Return Me.RegistroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RegistroField, value) <> true) Then
                    Me.RegistroField = value
                    Me.RaisePropertyChanged("Registro")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Signatura() As String
            Get
                Return Me.SignaturaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SignaturaField, value) <> true) Then
                    Me.SignaturaField = value
                    Me.RaisePropertyChanged("Signatura")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoDocumento() As String
            Get
                Return Me.TipoDocumentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoDocumentoField, value) <> true) Then
                    Me.TipoDocumentoField = value
                    Me.RaisePropertyChanged("TipoDocumento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoRegistro() As String
            Get
                Return Me.TipoRegistroField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoRegistroField, value) <> true) Then
                    Me.TipoRegistroField = value
                    Me.RaisePropertyChanged("TipoRegistro")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Titulo() As String
            Get
                Return Me.TituloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TituloField, value) <> true) Then
                    Me.TituloField = value
                    Me.RaisePropertyChanged("Titulo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DLibro", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DLibro
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ADQUISICIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUTOR1Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUTOR2Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AUTOR3Field As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CIUDADField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private COLACIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EDICIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EDITORAField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FECHAPUBLICACIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private GRADOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDIOMAField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ID_CIUDADField As System.Nullable(Of System.Guid)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ID_EDITORAField As System.Nullable(Of System.Guid)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ID_GRADOField As System.Nullable(Of System.Guid)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ID_IDIOMAField As System.Nullable(Of System.Guid)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ID_INSTITUCIONField As System.Nullable(Of System.Guid)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ID_LIBROField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ID_TUTORField As System.Nullable(Of System.Guid)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private INSTITUCIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ISBNField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NOTASField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OTRO_CODIGOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OTRO_TITULOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RESUMENField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SIGNATURAField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TIPODEDOCUMENTOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TIPOINVESTIGACIONField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TIPOREGISTROField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TITULOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TUTORField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VALORCORDOBAField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VALORDOLARField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VALORORIGINALField As Decimal
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ADQUISICION() As String
            Get
                Return Me.ADQUISICIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ADQUISICIONField, value) <> true) Then
                    Me.ADQUISICIONField = value
                    Me.RaisePropertyChanged("ADQUISICION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUTOR1() As String
            Get
                Return Me.AUTOR1Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUTOR1Field, value) <> true) Then
                    Me.AUTOR1Field = value
                    Me.RaisePropertyChanged("AUTOR1")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUTOR2() As String
            Get
                Return Me.AUTOR2Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUTOR2Field, value) <> true) Then
                    Me.AUTOR2Field = value
                    Me.RaisePropertyChanged("AUTOR2")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AUTOR3() As String
            Get
                Return Me.AUTOR3Field
            End Get
            Set
                If (Object.ReferenceEquals(Me.AUTOR3Field, value) <> true) Then
                    Me.AUTOR3Field = value
                    Me.RaisePropertyChanged("AUTOR3")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CIUDAD() As String
            Get
                Return Me.CIUDADField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CIUDADField, value) <> true) Then
                    Me.CIUDADField = value
                    Me.RaisePropertyChanged("CIUDAD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property COLACION() As String
            Get
                Return Me.COLACIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.COLACIONField, value) <> true) Then
                    Me.COLACIONField = value
                    Me.RaisePropertyChanged("COLACION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EDICION() As String
            Get
                Return Me.EDICIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EDICIONField, value) <> true) Then
                    Me.EDICIONField = value
                    Me.RaisePropertyChanged("EDICION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EDITORA() As String
            Get
                Return Me.EDITORAField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EDITORAField, value) <> true) Then
                    Me.EDITORAField = value
                    Me.RaisePropertyChanged("EDITORA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FECHAPUBLICACION() As String
            Get
                Return Me.FECHAPUBLICACIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FECHAPUBLICACIONField, value) <> true) Then
                    Me.FECHAPUBLICACIONField = value
                    Me.RaisePropertyChanged("FECHAPUBLICACION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property GRADO() As String
            Get
                Return Me.GRADOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.GRADOField, value) <> true) Then
                    Me.GRADOField = value
                    Me.RaisePropertyChanged("GRADO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IDIOMA() As String
            Get
                Return Me.IDIOMAField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IDIOMAField, value) <> true) Then
                    Me.IDIOMAField = value
                    Me.RaisePropertyChanged("IDIOMA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID_CIUDAD() As System.Nullable(Of System.Guid)
            Get
                Return Me.ID_CIUDADField
            End Get
            Set
                If (Me.ID_CIUDADField.Equals(value) <> true) Then
                    Me.ID_CIUDADField = value
                    Me.RaisePropertyChanged("ID_CIUDAD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID_EDITORA() As System.Nullable(Of System.Guid)
            Get
                Return Me.ID_EDITORAField
            End Get
            Set
                If (Me.ID_EDITORAField.Equals(value) <> true) Then
                    Me.ID_EDITORAField = value
                    Me.RaisePropertyChanged("ID_EDITORA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID_GRADO() As System.Nullable(Of System.Guid)
            Get
                Return Me.ID_GRADOField
            End Get
            Set
                If (Me.ID_GRADOField.Equals(value) <> true) Then
                    Me.ID_GRADOField = value
                    Me.RaisePropertyChanged("ID_GRADO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID_IDIOMA() As System.Nullable(Of System.Guid)
            Get
                Return Me.ID_IDIOMAField
            End Get
            Set
                If (Me.ID_IDIOMAField.Equals(value) <> true) Then
                    Me.ID_IDIOMAField = value
                    Me.RaisePropertyChanged("ID_IDIOMA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID_INSTITUCION() As System.Nullable(Of System.Guid)
            Get
                Return Me.ID_INSTITUCIONField
            End Get
            Set
                If (Me.ID_INSTITUCIONField.Equals(value) <> true) Then
                    Me.ID_INSTITUCIONField = value
                    Me.RaisePropertyChanged("ID_INSTITUCION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID_LIBRO() As System.Guid
            Get
                Return Me.ID_LIBROField
            End Get
            Set
                If (Me.ID_LIBROField.Equals(value) <> true) Then
                    Me.ID_LIBROField = value
                    Me.RaisePropertyChanged("ID_LIBRO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID_TUTOR() As System.Nullable(Of System.Guid)
            Get
                Return Me.ID_TUTORField
            End Get
            Set
                If (Me.ID_TUTORField.Equals(value) <> true) Then
                    Me.ID_TUTORField = value
                    Me.RaisePropertyChanged("ID_TUTOR")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property INSTITUCION() As String
            Get
                Return Me.INSTITUCIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.INSTITUCIONField, value) <> true) Then
                    Me.INSTITUCIONField = value
                    Me.RaisePropertyChanged("INSTITUCION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ISBN() As String
            Get
                Return Me.ISBNField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ISBNField, value) <> true) Then
                    Me.ISBNField = value
                    Me.RaisePropertyChanged("ISBN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NOTAS() As String
            Get
                Return Me.NOTASField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NOTASField, value) <> true) Then
                    Me.NOTASField = value
                    Me.RaisePropertyChanged("NOTAS")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OTRO_CODIGO() As String
            Get
                Return Me.OTRO_CODIGOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OTRO_CODIGOField, value) <> true) Then
                    Me.OTRO_CODIGOField = value
                    Me.RaisePropertyChanged("OTRO_CODIGO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OTRO_TITULO() As String
            Get
                Return Me.OTRO_TITULOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OTRO_TITULOField, value) <> true) Then
                    Me.OTRO_TITULOField = value
                    Me.RaisePropertyChanged("OTRO_TITULO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RESUMEN() As String
            Get
                Return Me.RESUMENField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RESUMENField, value) <> true) Then
                    Me.RESUMENField = value
                    Me.RaisePropertyChanged("RESUMEN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SIGNATURA() As String
            Get
                Return Me.SIGNATURAField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SIGNATURAField, value) <> true) Then
                    Me.SIGNATURAField = value
                    Me.RaisePropertyChanged("SIGNATURA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TIPODEDOCUMENTO() As String
            Get
                Return Me.TIPODEDOCUMENTOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TIPODEDOCUMENTOField, value) <> true) Then
                    Me.TIPODEDOCUMENTOField = value
                    Me.RaisePropertyChanged("TIPODEDOCUMENTO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TIPOINVESTIGACION() As String
            Get
                Return Me.TIPOINVESTIGACIONField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TIPOINVESTIGACIONField, value) <> true) Then
                    Me.TIPOINVESTIGACIONField = value
                    Me.RaisePropertyChanged("TIPOINVESTIGACION")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TIPOREGISTRO() As String
            Get
                Return Me.TIPOREGISTROField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TIPOREGISTROField, value) <> true) Then
                    Me.TIPOREGISTROField = value
                    Me.RaisePropertyChanged("TIPOREGISTRO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TITULO() As String
            Get
                Return Me.TITULOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TITULOField, value) <> true) Then
                    Me.TITULOField = value
                    Me.RaisePropertyChanged("TITULO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TUTOR() As String
            Get
                Return Me.TUTORField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TUTORField, value) <> true) Then
                    Me.TUTORField = value
                    Me.RaisePropertyChanged("TUTOR")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VALORCORDOBA() As Decimal
            Get
                Return Me.VALORCORDOBAField
            End Get
            Set
                If (Me.VALORCORDOBAField.Equals(value) <> true) Then
                    Me.VALORCORDOBAField = value
                    Me.RaisePropertyChanged("VALORCORDOBA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VALORDOLAR() As Decimal
            Get
                Return Me.VALORDOLARField
            End Get
            Set
                If (Me.VALORDOLARField.Equals(value) <> true) Then
                    Me.VALORDOLARField = value
                    Me.RaisePropertyChanged("VALORDOLAR")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property VALORORIGINAL() As Decimal
            Get
                Return Me.VALORORIGINALField
            End Get
            Set
                If (Me.VALORORIGINALField.Equals(value) <> true) Then
                    Me.VALORORIGINALField = value
                    Me.RaisePropertyChanged("VALORORIGINAL")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="InventarioServicio.IInventarioServicio")>  _
    Public Interface IInventarioServicio
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/DoWork", ReplyAction:="http://tempuri.org/IInventarioServicio/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/DoWork", ReplyAction:="http://tempuri.org/IInventarioServicio/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/Guardar", ReplyAction:="http://tempuri.org/IInventarioServicio/GuardarResponse")>  _
        Sub Guardar(ByVal Inventario As InventarioServicio.DInventario)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/Guardar", ReplyAction:="http://tempuri.org/IInventarioServicio/GuardarResponse")>  _
        Function GuardarAsync(ByVal Inventario As InventarioServicio.DInventario) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/Editar", ReplyAction:="http://tempuri.org/IInventarioServicio/EditarResponse")>  _
        Sub Editar(ByVal Inventario As InventarioServicio.DInventario)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/Editar", ReplyAction:="http://tempuri.org/IInventarioServicio/EditarResponse")>  _
        Function EditarAsync(ByVal Inventario As InventarioServicio.DInventario) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/Eliminar", ReplyAction:="http://tempuri.org/IInventarioServicio/EliminarResponse")>  _
        Sub Eliminar(ByVal IdInventario As System.Guid)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/Eliminar", ReplyAction:="http://tempuri.org/IInventarioServicio/EliminarResponse")>  _
        Function EliminarAsync(ByVal IdInventario As System.Guid) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/BuscarPorId", ReplyAction:="http://tempuri.org/IInventarioServicio/BuscarPorIdResponse")>  _
        Function BuscarPorId(ByVal IdInventario As System.Guid) As InventarioServicio.DInventario
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/BuscarPorId", ReplyAction:="http://tempuri.org/IInventarioServicio/BuscarPorIdResponse")>  _
        Function BuscarPorIdAsync(ByVal IdInventario As System.Guid) As System.Threading.Tasks.Task(Of InventarioServicio.DInventario)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/BuscarPorRegistro", ReplyAction:="http://tempuri.org/IInventarioServicio/BuscarPorRegistroResponse")>  _
        Function BuscarPorRegistro(ByVal Registro As String) As InventarioServicio.DInventario
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/BuscarPorRegistro", ReplyAction:="http://tempuri.org/IInventarioServicio/BuscarPorRegistroResponse")>  _
        Function BuscarPorRegistroAsync(ByVal Registro As String) As System.Threading.Tasks.Task(Of InventarioServicio.DInventario)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/Busqueda", ReplyAction:="http://tempuri.org/IInventarioServicio/BusquedaResponse")>  _
        Function Busqueda(ByVal Libro As InventarioServicio.DLibro, ByVal Registro As String) As System.Collections.Generic.List(Of InventarioServicio.DInventario)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/Busqueda", ReplyAction:="http://tempuri.org/IInventarioServicio/BusquedaResponse")>  _
        Function BusquedaAsync(ByVal Libro As InventarioServicio.DLibro, ByVal Registro As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of InventarioServicio.DInventario))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/CopiasDeLibro", ReplyAction:="http://tempuri.org/IInventarioServicio/CopiasDeLibroResponse")>  _
        Function CopiasDeLibro(ByVal IdLibro As System.Guid) As System.Collections.Generic.List(Of InventarioServicio.DInventario)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IInventarioServicio/CopiasDeLibro", ReplyAction:="http://tempuri.org/IInventarioServicio/CopiasDeLibroResponse")>  _
        Function CopiasDeLibroAsync(ByVal IdLibro As System.Guid) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of InventarioServicio.DInventario))
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IInventarioServicioChannel
        Inherits InventarioServicio.IInventarioServicio, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class InventarioServicioClient
        Inherits System.ServiceModel.ClientBase(Of InventarioServicio.IInventarioServicio)
        Implements InventarioServicio.IInventarioServicio
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements InventarioServicio.IInventarioServicio.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements InventarioServicio.IInventarioServicio.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
        
        Public Sub Guardar(ByVal Inventario As InventarioServicio.DInventario) Implements InventarioServicio.IInventarioServicio.Guardar
            MyBase.Channel.Guardar(Inventario)
        End Sub
        
        Public Function GuardarAsync(ByVal Inventario As InventarioServicio.DInventario) As System.Threading.Tasks.Task Implements InventarioServicio.IInventarioServicio.GuardarAsync
            Return MyBase.Channel.GuardarAsync(Inventario)
        End Function
        
        Public Sub Editar(ByVal Inventario As InventarioServicio.DInventario) Implements InventarioServicio.IInventarioServicio.Editar
            MyBase.Channel.Editar(Inventario)
        End Sub
        
        Public Function EditarAsync(ByVal Inventario As InventarioServicio.DInventario) As System.Threading.Tasks.Task Implements InventarioServicio.IInventarioServicio.EditarAsync
            Return MyBase.Channel.EditarAsync(Inventario)
        End Function
        
        Public Sub Eliminar(ByVal IdInventario As System.Guid) Implements InventarioServicio.IInventarioServicio.Eliminar
            MyBase.Channel.Eliminar(IdInventario)
        End Sub
        
        Public Function EliminarAsync(ByVal IdInventario As System.Guid) As System.Threading.Tasks.Task Implements InventarioServicio.IInventarioServicio.EliminarAsync
            Return MyBase.Channel.EliminarAsync(IdInventario)
        End Function
        
        Public Function BuscarPorId(ByVal IdInventario As System.Guid) As InventarioServicio.DInventario Implements InventarioServicio.IInventarioServicio.BuscarPorId
            Return MyBase.Channel.BuscarPorId(IdInventario)
        End Function
        
        Public Function BuscarPorIdAsync(ByVal IdInventario As System.Guid) As System.Threading.Tasks.Task(Of InventarioServicio.DInventario) Implements InventarioServicio.IInventarioServicio.BuscarPorIdAsync
            Return MyBase.Channel.BuscarPorIdAsync(IdInventario)
        End Function
        
        Public Function BuscarPorRegistro(ByVal Registro As String) As InventarioServicio.DInventario Implements InventarioServicio.IInventarioServicio.BuscarPorRegistro
            Return MyBase.Channel.BuscarPorRegistro(Registro)
        End Function
        
        Public Function BuscarPorRegistroAsync(ByVal Registro As String) As System.Threading.Tasks.Task(Of InventarioServicio.DInventario) Implements InventarioServicio.IInventarioServicio.BuscarPorRegistroAsync
            Return MyBase.Channel.BuscarPorRegistroAsync(Registro)
        End Function
        
        Public Function Busqueda(ByVal Libro As InventarioServicio.DLibro, ByVal Registro As String) As System.Collections.Generic.List(Of InventarioServicio.DInventario) Implements InventarioServicio.IInventarioServicio.Busqueda
            Return MyBase.Channel.Busqueda(Libro, Registro)
        End Function
        
        Public Function BusquedaAsync(ByVal Libro As InventarioServicio.DLibro, ByVal Registro As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of InventarioServicio.DInventario)) Implements InventarioServicio.IInventarioServicio.BusquedaAsync
            Return MyBase.Channel.BusquedaAsync(Libro, Registro)
        End Function
        
        Public Function CopiasDeLibro(ByVal IdLibro As System.Guid) As System.Collections.Generic.List(Of InventarioServicio.DInventario) Implements InventarioServicio.IInventarioServicio.CopiasDeLibro
            Return MyBase.Channel.CopiasDeLibro(IdLibro)
        End Function
        
        Public Function CopiasDeLibroAsync(ByVal IdLibro As System.Guid) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of InventarioServicio.DInventario)) Implements InventarioServicio.IInventarioServicio.CopiasDeLibroAsync
            Return MyBase.Channel.CopiasDeLibroAsync(IdLibro)
        End Function
    End Class
End Namespace
