'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace RecomendacionServicio
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DRecomendacion", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DRecomendacion
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AreaDirigidaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AutoresField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EdicionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaModField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaRegField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdRecomendacionField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdUsuarioField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IsbnField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NotaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OtroTituloField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TituloField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UsuarioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VolumenField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As Boolean
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property AreaDirigida() As String
            Get
                Return Me.AreaDirigidaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AreaDirigidaField, value) <> true) Then
                    Me.AreaDirigidaField = value
                    Me.RaisePropertyChanged("AreaDirigida")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Autores() As String
            Get
                Return Me.AutoresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AutoresField, value) <> true) Then
                    Me.AutoresField = value
                    Me.RaisePropertyChanged("Autores")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Edicion() As String
            Get
                Return Me.EdicionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EdicionField, value) <> true) Then
                    Me.EdicionField = value
                    Me.RaisePropertyChanged("Edicion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaMod() As Date
            Get
                Return Me.FechaModField
            End Get
            Set
                If (Me.FechaModField.Equals(value) <> true) Then
                    Me.FechaModField = value
                    Me.RaisePropertyChanged("FechaMod")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaReg() As Date
            Get
                Return Me.FechaRegField
            End Get
            Set
                If (Me.FechaRegField.Equals(value) <> true) Then
                    Me.FechaRegField = value
                    Me.RaisePropertyChanged("FechaReg")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdRecomendacion() As System.Guid
            Get
                Return Me.IdRecomendacionField
            End Get
            Set
                If (Me.IdRecomendacionField.Equals(value) <> true) Then
                    Me.IdRecomendacionField = value
                    Me.RaisePropertyChanged("IdRecomendacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdUsuario() As System.Guid
            Get
                Return Me.IdUsuarioField
            End Get
            Set
                If (Me.IdUsuarioField.Equals(value) <> true) Then
                    Me.IdUsuarioField = value
                    Me.RaisePropertyChanged("IdUsuario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Isbn() As String
            Get
                Return Me.IsbnField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IsbnField, value) <> true) Then
                    Me.IsbnField = value
                    Me.RaisePropertyChanged("Isbn")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nota() As String
            Get
                Return Me.NotaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NotaField, value) <> true) Then
                    Me.NotaField = value
                    Me.RaisePropertyChanged("Nota")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OtroTitulo() As String
            Get
                Return Me.OtroTituloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.OtroTituloField, value) <> true) Then
                    Me.OtroTituloField = value
                    Me.RaisePropertyChanged("OtroTitulo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Titulo() As String
            Get
                Return Me.TituloField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TituloField, value) <> true) Then
                    Me.TituloField = value
                    Me.RaisePropertyChanged("Titulo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Usuario() As String
            Get
                Return Me.UsuarioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UsuarioField, value) <> true) Then
                    Me.UsuarioField = value
                    Me.RaisePropertyChanged("Usuario")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Volumen() As String
            Get
                Return Me.VolumenField
            End Get
            Set
                If (Object.ReferenceEquals(Me.VolumenField, value) <> true) Then
                    Me.VolumenField = value
                    Me.RaisePropertyChanged("Volumen")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DCantidadMensual", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DCantidadMensual
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CantidadField As Decimal
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MesField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Cantidad() As Decimal
            Get
                Return Me.CantidadField
            End Get
            Set
                If (Me.CantidadField.Equals(value) <> true) Then
                    Me.CantidadField = value
                    Me.RaisePropertyChanged("Cantidad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Mes() As String
            Get
                Return Me.MesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MesField, value) <> true) Then
                    Me.MesField = value
                    Me.RaisePropertyChanged("Mes")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="RecomendacionServicio.IRecomendacionServicio")>  _
    Public Interface IRecomendacionServicio
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRecomendacionServicio/DoWork", ReplyAction:="http://tempuri.org/IRecomendacionServicio/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRecomendacionServicio/DoWork", ReplyAction:="http://tempuri.org/IRecomendacionServicio/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRecomendacionServicio/Guardar", ReplyAction:="http://tempuri.org/IRecomendacionServicio/GuardarResponse")>  _
        Function Guardar(ByVal Recomendacion As RecomendacionServicio.DRecomendacion) As System.Guid
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRecomendacionServicio/Guardar", ReplyAction:="http://tempuri.org/IRecomendacionServicio/GuardarResponse")>  _
        Function GuardarAsync(ByVal Recomendacion As RecomendacionServicio.DRecomendacion) As System.Threading.Tasks.Task(Of System.Guid)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRecomendacionServicio/CantidadAnual", ReplyAction:="http://tempuri.org/IRecomendacionServicio/CantidadAnualResponse")>  _
        Function CantidadAnual() As System.Collections.Generic.List(Of RecomendacionServicio.DCantidadMensual)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRecomendacionServicio/CantidadAnual", ReplyAction:="http://tempuri.org/IRecomendacionServicio/CantidadAnualResponse")>  _
        Function CantidadAnualAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RecomendacionServicio.DCantidadMensual))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRecomendacionServicio/Busqueda", ReplyAction:="http://tempuri.org/IRecomendacionServicio/BusquedaResponse")>  _
        Function Busqueda(ByVal Inicio As Date, ByVal Fin As Date, ByVal NombreUsuario As String) As System.Collections.Generic.List(Of RecomendacionServicio.DRecomendacion)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRecomendacionServicio/Busqueda", ReplyAction:="http://tempuri.org/IRecomendacionServicio/BusquedaResponse")>  _
        Function BusquedaAsync(ByVal Inicio As Date, ByVal Fin As Date, ByVal NombreUsuario As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RecomendacionServicio.DRecomendacion))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRecomendacionServicio/RecomendacionesUsers", ReplyAction:="http://tempuri.org/IRecomendacionServicio/RecomendacionesUsersResponse")>  _
        Function RecomendacionesUsers(ByVal Inicio As Date, ByVal Fin As Date, ByVal IdUsuario As System.Guid) As System.Collections.Generic.List(Of RecomendacionServicio.DRecomendacion)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRecomendacionServicio/RecomendacionesUsers", ReplyAction:="http://tempuri.org/IRecomendacionServicio/RecomendacionesUsersResponse")>  _
        Function RecomendacionesUsersAsync(ByVal Inicio As Date, ByVal Fin As Date, ByVal IdUsuario As System.Guid) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RecomendacionServicio.DRecomendacion))
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IRecomendacionServicioChannel
        Inherits RecomendacionServicio.IRecomendacionServicio, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class RecomendacionServicioClient
        Inherits System.ServiceModel.ClientBase(Of RecomendacionServicio.IRecomendacionServicio)
        Implements RecomendacionServicio.IRecomendacionServicio
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements RecomendacionServicio.IRecomendacionServicio.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements RecomendacionServicio.IRecomendacionServicio.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
        
        Public Function Guardar(ByVal Recomendacion As RecomendacionServicio.DRecomendacion) As System.Guid Implements RecomendacionServicio.IRecomendacionServicio.Guardar
            Return MyBase.Channel.Guardar(Recomendacion)
        End Function
        
        Public Function GuardarAsync(ByVal Recomendacion As RecomendacionServicio.DRecomendacion) As System.Threading.Tasks.Task(Of System.Guid) Implements RecomendacionServicio.IRecomendacionServicio.GuardarAsync
            Return MyBase.Channel.GuardarAsync(Recomendacion)
        End Function
        
        Public Function CantidadAnual() As System.Collections.Generic.List(Of RecomendacionServicio.DCantidadMensual) Implements RecomendacionServicio.IRecomendacionServicio.CantidadAnual
            Return MyBase.Channel.CantidadAnual
        End Function
        
        Public Function CantidadAnualAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RecomendacionServicio.DCantidadMensual)) Implements RecomendacionServicio.IRecomendacionServicio.CantidadAnualAsync
            Return MyBase.Channel.CantidadAnualAsync
        End Function
        
        Public Function Busqueda(ByVal Inicio As Date, ByVal Fin As Date, ByVal NombreUsuario As String) As System.Collections.Generic.List(Of RecomendacionServicio.DRecomendacion) Implements RecomendacionServicio.IRecomendacionServicio.Busqueda
            Return MyBase.Channel.Busqueda(Inicio, Fin, NombreUsuario)
        End Function
        
        Public Function BusquedaAsync(ByVal Inicio As Date, ByVal Fin As Date, ByVal NombreUsuario As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RecomendacionServicio.DRecomendacion)) Implements RecomendacionServicio.IRecomendacionServicio.BusquedaAsync
            Return MyBase.Channel.BusquedaAsync(Inicio, Fin, NombreUsuario)
        End Function
        
        Public Function RecomendacionesUsers(ByVal Inicio As Date, ByVal Fin As Date, ByVal IdUsuario As System.Guid) As System.Collections.Generic.List(Of RecomendacionServicio.DRecomendacion) Implements RecomendacionServicio.IRecomendacionServicio.RecomendacionesUsers
            Return MyBase.Channel.RecomendacionesUsers(Inicio, Fin, IdUsuario)
        End Function
        
        Public Function RecomendacionesUsersAsync(ByVal Inicio As Date, ByVal Fin As Date, ByVal IdUsuario As System.Guid) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of RecomendacionServicio.DRecomendacion)) Implements RecomendacionServicio.IRecomendacionServicio.RecomendacionesUsersAsync
            Return MyBase.Channel.RecomendacionesUsersAsync(Inicio, Fin, IdUsuario)
        End Function
    End Class
End Namespace
