'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace CarreraServicio
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DCarrera", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DCarrera
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdCarreraField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombreCarreraField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdCarrera() As System.Guid
            Get
                Return Me.IdCarreraField
            End Get
            Set
                If (Me.IdCarreraField.Equals(value) <> true) Then
                    Me.IdCarreraField = value
                    Me.RaisePropertyChanged("IdCarrera")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property N() As Long
            Get
                Return Me.NField
            End Get
            Set
                If (Me.NField.Equals(value) <> true) Then
                    Me.NField = value
                    Me.RaisePropertyChanged("N")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NombreCarrera() As String
            Get
                Return Me.NombreCarreraField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombreCarreraField, value) <> true) Then
                    Me.NombreCarreraField = value
                    Me.RaisePropertyChanged("NombreCarrera")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="CarreraServicio.ICarreraServicio")>  _
    Public Interface ICarreraServicio
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICarreraServicio/DoWork", ReplyAction:="http://tempuri.org/ICarreraServicio/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICarreraServicio/DoWork", ReplyAction:="http://tempuri.org/ICarreraServicio/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICarreraServicio/Lista", ReplyAction:="http://tempuri.org/ICarreraServicio/ListaResponse")>  _
        Function Lista() As System.Collections.Generic.List(Of CarreraServicio.DCarrera)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICarreraServicio/Lista", ReplyAction:="http://tempuri.org/ICarreraServicio/ListaResponse")>  _
        Function ListaAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CarreraServicio.DCarrera))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICarreraServicio/Filtrar", ReplyAction:="http://tempuri.org/ICarreraServicio/FiltrarResponse")>  _
        Function Filtrar(ByVal Nombre As String) As System.Collections.Generic.List(Of CarreraServicio.DCarrera)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICarreraServicio/Filtrar", ReplyAction:="http://tempuri.org/ICarreraServicio/FiltrarResponse")>  _
        Function FiltrarAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CarreraServicio.DCarrera))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICarreraServicio/Guardar", ReplyAction:="http://tempuri.org/ICarreraServicio/GuardarResponse")>  _
        Sub Guardar(ByVal Carrera As CarreraServicio.DCarrera)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICarreraServicio/Guardar", ReplyAction:="http://tempuri.org/ICarreraServicio/GuardarResponse")>  _
        Function GuardarAsync(ByVal Carrera As CarreraServicio.DCarrera) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICarreraServicio/BuscarPorNombre", ReplyAction:="http://tempuri.org/ICarreraServicio/BuscarPorNombreResponse")>  _
        Function BuscarPorNombre(ByVal Nombre As String) As CarreraServicio.DCarrera
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICarreraServicio/BuscarPorNombre", ReplyAction:="http://tempuri.org/ICarreraServicio/BuscarPorNombreResponse")>  _
        Function BuscarPorNombreAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of CarreraServicio.DCarrera)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICarreraServicio/BuscarPorId", ReplyAction:="http://tempuri.org/ICarreraServicio/BuscarPorIdResponse")>  _
        Function BuscarPorId(ByVal IdCarrera As System.Guid) As CarreraServicio.DCarrera
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICarreraServicio/BuscarPorId", ReplyAction:="http://tempuri.org/ICarreraServicio/BuscarPorIdResponse")>  _
        Function BuscarPorIdAsync(ByVal IdCarrera As System.Guid) As System.Threading.Tasks.Task(Of CarreraServicio.DCarrera)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ICarreraServicioChannel
        Inherits CarreraServicio.ICarreraServicio, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class CarreraServicioClient
        Inherits System.ServiceModel.ClientBase(Of CarreraServicio.ICarreraServicio)
        Implements CarreraServicio.ICarreraServicio
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements CarreraServicio.ICarreraServicio.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements CarreraServicio.ICarreraServicio.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
        
        Public Function Lista() As System.Collections.Generic.List(Of CarreraServicio.DCarrera) Implements CarreraServicio.ICarreraServicio.Lista
            Return MyBase.Channel.Lista
        End Function
        
        Public Function ListaAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CarreraServicio.DCarrera)) Implements CarreraServicio.ICarreraServicio.ListaAsync
            Return MyBase.Channel.ListaAsync
        End Function
        
        Public Function Filtrar(ByVal Nombre As String) As System.Collections.Generic.List(Of CarreraServicio.DCarrera) Implements CarreraServicio.ICarreraServicio.Filtrar
            Return MyBase.Channel.Filtrar(Nombre)
        End Function
        
        Public Function FiltrarAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of CarreraServicio.DCarrera)) Implements CarreraServicio.ICarreraServicio.FiltrarAsync
            Return MyBase.Channel.FiltrarAsync(Nombre)
        End Function
        
        Public Sub Guardar(ByVal Carrera As CarreraServicio.DCarrera) Implements CarreraServicio.ICarreraServicio.Guardar
            MyBase.Channel.Guardar(Carrera)
        End Sub
        
        Public Function GuardarAsync(ByVal Carrera As CarreraServicio.DCarrera) As System.Threading.Tasks.Task Implements CarreraServicio.ICarreraServicio.GuardarAsync
            Return MyBase.Channel.GuardarAsync(Carrera)
        End Function
        
        Public Function BuscarPorNombre(ByVal Nombre As String) As CarreraServicio.DCarrera Implements CarreraServicio.ICarreraServicio.BuscarPorNombre
            Return MyBase.Channel.BuscarPorNombre(Nombre)
        End Function
        
        Public Function BuscarPorNombreAsync(ByVal Nombre As String) As System.Threading.Tasks.Task(Of CarreraServicio.DCarrera) Implements CarreraServicio.ICarreraServicio.BuscarPorNombreAsync
            Return MyBase.Channel.BuscarPorNombreAsync(Nombre)
        End Function
        
        Public Function BuscarPorId(ByVal IdCarrera As System.Guid) As CarreraServicio.DCarrera Implements CarreraServicio.ICarreraServicio.BuscarPorId
            Return MyBase.Channel.BuscarPorId(IdCarrera)
        End Function
        
        Public Function BuscarPorIdAsync(ByVal IdCarrera As System.Guid) As System.Threading.Tasks.Task(Of CarreraServicio.DCarrera) Implements CarreraServicio.ICarreraServicio.BuscarPorIdAsync
            Return MyBase.Channel.BuscarPorIdAsync(IdCarrera)
        End Function
    End Class
End Namespace
