'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace IdiomaServicio
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DIdioma", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DIdioma
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DescripcionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdIdiomaField As System.Guid
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Descripcion() As String
            Get
                Return Me.DescripcionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DescripcionField, value) <> true) Then
                    Me.DescripcionField = value
                    Me.RaisePropertyChanged("Descripcion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdIdioma() As System.Guid
            Get
                Return Me.IdIdiomaField
            End Get
            Set
                If (Me.IdIdiomaField.Equals(value) <> true) Then
                    Me.IdIdiomaField = value
                    Me.RaisePropertyChanged("IdIdioma")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="IdiomaServicio.IIdiomaServicio")>  _
    Public Interface IIdiomaServicio
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIdiomaServicio/DoWork", ReplyAction:="http://tempuri.org/IIdiomaServicio/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIdiomaServicio/DoWork", ReplyAction:="http://tempuri.org/IIdiomaServicio/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIdiomaServicio/Guardar", ReplyAction:="http://tempuri.org/IIdiomaServicio/GuardarResponse")>  _
        Sub Guardar(ByVal Idioma As IdiomaServicio.DIdioma)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIdiomaServicio/Guardar", ReplyAction:="http://tempuri.org/IIdiomaServicio/GuardarResponse")>  _
        Function GuardarAsync(ByVal Idioma As IdiomaServicio.DIdioma) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIdiomaServicio/Lista", ReplyAction:="http://tempuri.org/IIdiomaServicio/ListaResponse")>  _
        Function Lista() As System.Collections.Generic.List(Of IdiomaServicio.DIdioma)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIdiomaServicio/Lista", ReplyAction:="http://tempuri.org/IIdiomaServicio/ListaResponse")>  _
        Function ListaAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of IdiomaServicio.DIdioma))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIdiomaServicio/BuscarPorDescripcion", ReplyAction:="http://tempuri.org/IIdiomaServicio/BuscarPorDescripcionResponse")>  _
        Function BuscarPorDescripcion(ByVal Descripcion As String) As IdiomaServicio.DIdioma
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIdiomaServicio/BuscarPorDescripcion", ReplyAction:="http://tempuri.org/IIdiomaServicio/BuscarPorDescripcionResponse")>  _
        Function BuscarPorDescripcionAsync(ByVal Descripcion As String) As System.Threading.Tasks.Task(Of IdiomaServicio.DIdioma)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIdiomaServicio/Existe", ReplyAction:="http://tempuri.org/IIdiomaServicio/ExisteResponse")>  _
        Function Existe(ByVal Descripcion As String) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IIdiomaServicio/Existe", ReplyAction:="http://tempuri.org/IIdiomaServicio/ExisteResponse")>  _
        Function ExisteAsync(ByVal Descripcion As String) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IIdiomaServicioChannel
        Inherits IdiomaServicio.IIdiomaServicio, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class IdiomaServicioClient
        Inherits System.ServiceModel.ClientBase(Of IdiomaServicio.IIdiomaServicio)
        Implements IdiomaServicio.IIdiomaServicio
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements IdiomaServicio.IIdiomaServicio.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements IdiomaServicio.IIdiomaServicio.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
        
        Public Sub Guardar(ByVal Idioma As IdiomaServicio.DIdioma) Implements IdiomaServicio.IIdiomaServicio.Guardar
            MyBase.Channel.Guardar(Idioma)
        End Sub
        
        Public Function GuardarAsync(ByVal Idioma As IdiomaServicio.DIdioma) As System.Threading.Tasks.Task Implements IdiomaServicio.IIdiomaServicio.GuardarAsync
            Return MyBase.Channel.GuardarAsync(Idioma)
        End Function
        
        Public Function Lista() As System.Collections.Generic.List(Of IdiomaServicio.DIdioma) Implements IdiomaServicio.IIdiomaServicio.Lista
            Return MyBase.Channel.Lista
        End Function
        
        Public Function ListaAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of IdiomaServicio.DIdioma)) Implements IdiomaServicio.IIdiomaServicio.ListaAsync
            Return MyBase.Channel.ListaAsync
        End Function
        
        Public Function BuscarPorDescripcion(ByVal Descripcion As String) As IdiomaServicio.DIdioma Implements IdiomaServicio.IIdiomaServicio.BuscarPorDescripcion
            Return MyBase.Channel.BuscarPorDescripcion(Descripcion)
        End Function
        
        Public Function BuscarPorDescripcionAsync(ByVal Descripcion As String) As System.Threading.Tasks.Task(Of IdiomaServicio.DIdioma) Implements IdiomaServicio.IIdiomaServicio.BuscarPorDescripcionAsync
            Return MyBase.Channel.BuscarPorDescripcionAsync(Descripcion)
        End Function
        
        Public Function Existe(ByVal Descripcion As String) As Boolean Implements IdiomaServicio.IIdiomaServicio.Existe
            Return MyBase.Channel.Existe(Descripcion)
        End Function
        
        Public Function ExisteAsync(ByVal Descripcion As String) As System.Threading.Tasks.Task(Of Boolean) Implements IdiomaServicio.IIdiomaServicio.ExisteAsync
            Return MyBase.Channel.ExisteAsync(Descripcion)
        End Function
    End Class
End Namespace
