'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.17929
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace PersonaServicio
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DPersona", [Namespace]:="http://schemas.datacontract.org/2004/07/ServiciosWeb"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DPersona
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ActivoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ApellidosField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private AreaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CarreraField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CiudadField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartamentoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartamentoAcademicoDocenteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DepartamentoAcademicoEstudianteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DomicilioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaNacimientoField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaRegistroField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaUltimaModificacionField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdCarreraField As System.Nullable(Of System.Guid)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdCiudadField As System.Nullable(Of System.Guid)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdPersonaField As System.Guid
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IdentificacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MunicipioField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NCarnetField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NombresField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ObservacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PaisField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SexoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TelefonoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoIdentificacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TipoPersonaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TurnoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Activo() As Boolean
            Get
                Return Me.ActivoField
            End Get
            Set
                If (Me.ActivoField.Equals(value) <> true) Then
                    Me.ActivoField = value
                    Me.RaisePropertyChanged("Activo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Apellidos() As String
            Get
                Return Me.ApellidosField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ApellidosField, value) <> true) Then
                    Me.ApellidosField = value
                    Me.RaisePropertyChanged("Apellidos")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Area() As String
            Get
                Return Me.AreaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.AreaField, value) <> true) Then
                    Me.AreaField = value
                    Me.RaisePropertyChanged("Area")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Carrera() As String
            Get
                Return Me.CarreraField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CarreraField, value) <> true) Then
                    Me.CarreraField = value
                    Me.RaisePropertyChanged("Carrera")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Ciudad() As String
            Get
                Return Me.CiudadField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CiudadField, value) <> true) Then
                    Me.CiudadField = value
                    Me.RaisePropertyChanged("Ciudad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Departamento() As String
            Get
                Return Me.DepartamentoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartamentoField, value) <> true) Then
                    Me.DepartamentoField = value
                    Me.RaisePropertyChanged("Departamento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DepartamentoAcademicoDocente() As String
            Get
                Return Me.DepartamentoAcademicoDocenteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartamentoAcademicoDocenteField, value) <> true) Then
                    Me.DepartamentoAcademicoDocenteField = value
                    Me.RaisePropertyChanged("DepartamentoAcademicoDocente")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DepartamentoAcademicoEstudiante() As String
            Get
                Return Me.DepartamentoAcademicoEstudianteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DepartamentoAcademicoEstudianteField, value) <> true) Then
                    Me.DepartamentoAcademicoEstudianteField = value
                    Me.RaisePropertyChanged("DepartamentoAcademicoEstudiante")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Domicilio() As String
            Get
                Return Me.DomicilioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DomicilioField, value) <> true) Then
                    Me.DomicilioField = value
                    Me.RaisePropertyChanged("Domicilio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaNacimiento() As Date
            Get
                Return Me.FechaNacimientoField
            End Get
            Set
                If (Me.FechaNacimientoField.Equals(value) <> true) Then
                    Me.FechaNacimientoField = value
                    Me.RaisePropertyChanged("FechaNacimiento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaRegistro() As Date
            Get
                Return Me.FechaRegistroField
            End Get
            Set
                If (Me.FechaRegistroField.Equals(value) <> true) Then
                    Me.FechaRegistroField = value
                    Me.RaisePropertyChanged("FechaRegistro")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaUltimaModificacion() As Date
            Get
                Return Me.FechaUltimaModificacionField
            End Get
            Set
                If (Me.FechaUltimaModificacionField.Equals(value) <> true) Then
                    Me.FechaUltimaModificacionField = value
                    Me.RaisePropertyChanged("FechaUltimaModificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdCarrera() As System.Nullable(Of System.Guid)
            Get
                Return Me.IdCarreraField
            End Get
            Set
                If (Me.IdCarreraField.Equals(value) <> true) Then
                    Me.IdCarreraField = value
                    Me.RaisePropertyChanged("IdCarrera")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdCiudad() As System.Nullable(Of System.Guid)
            Get
                Return Me.IdCiudadField
            End Get
            Set
                If (Me.IdCiudadField.Equals(value) <> true) Then
                    Me.IdCiudadField = value
                    Me.RaisePropertyChanged("IdCiudad")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property IdPersona() As System.Guid
            Get
                Return Me.IdPersonaField
            End Get
            Set
                If (Me.IdPersonaField.Equals(value) <> true) Then
                    Me.IdPersonaField = value
                    Me.RaisePropertyChanged("IdPersona")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Identificacion() As String
            Get
                Return Me.IdentificacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.IdentificacionField, value) <> true) Then
                    Me.IdentificacionField = value
                    Me.RaisePropertyChanged("Identificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Municipio() As String
            Get
                Return Me.MunicipioField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MunicipioField, value) <> true) Then
                    Me.MunicipioField = value
                    Me.RaisePropertyChanged("Municipio")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property N() As Long
            Get
                Return Me.NField
            End Get
            Set
                If (Me.NField.Equals(value) <> true) Then
                    Me.NField = value
                    Me.RaisePropertyChanged("N")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NCarnet() As String
            Get
                Return Me.NCarnetField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NCarnetField, value) <> true) Then
                    Me.NCarnetField = value
                    Me.RaisePropertyChanged("NCarnet")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Nombres() As String
            Get
                Return Me.NombresField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NombresField, value) <> true) Then
                    Me.NombresField = value
                    Me.RaisePropertyChanged("Nombres")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Observacion() As String
            Get
                Return Me.ObservacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ObservacionField, value) <> true) Then
                    Me.ObservacionField = value
                    Me.RaisePropertyChanged("Observacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Pais() As String
            Get
                Return Me.PaisField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PaisField, value) <> true) Then
                    Me.PaisField = value
                    Me.RaisePropertyChanged("Pais")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Sexo() As Boolean
            Get
                Return Me.SexoField
            End Get
            Set
                If (Me.SexoField.Equals(value) <> true) Then
                    Me.SexoField = value
                    Me.RaisePropertyChanged("Sexo")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Telefono() As String
            Get
                Return Me.TelefonoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TelefonoField, value) <> true) Then
                    Me.TelefonoField = value
                    Me.RaisePropertyChanged("Telefono")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoIdentificacion() As String
            Get
                Return Me.TipoIdentificacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoIdentificacionField, value) <> true) Then
                    Me.TipoIdentificacionField = value
                    Me.RaisePropertyChanged("TipoIdentificacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TipoPersona() As String
            Get
                Return Me.TipoPersonaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TipoPersonaField, value) <> true) Then
                    Me.TipoPersonaField = value
                    Me.RaisePropertyChanged("TipoPersona")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Turno() As String
            Get
                Return Me.TurnoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TurnoField, value) <> true) Then
                    Me.TurnoField = value
                    Me.RaisePropertyChanged("Turno")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="PersonaServicio.IPersonaServicio")>  _
    Public Interface IPersonaServicio
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/DoWork", ReplyAction:="http://tempuri.org/IPersonaServicio/DoWorkResponse")>  _
        Sub DoWork()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/DoWork", ReplyAction:="http://tempuri.org/IPersonaServicio/DoWorkResponse")>  _
        Function DoWorkAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/Guardar", ReplyAction:="http://tempuri.org/IPersonaServicio/GuardarResponse")>  _
        Sub Guardar(ByVal Persona As PersonaServicio.DPersona)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/Guardar", ReplyAction:="http://tempuri.org/IPersonaServicio/GuardarResponse")>  _
        Function GuardarAsync(ByVal Persona As PersonaServicio.DPersona) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/Editar", ReplyAction:="http://tempuri.org/IPersonaServicio/EditarResponse")>  _
        Sub Editar(ByVal Persona As PersonaServicio.DPersona)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/Editar", ReplyAction:="http://tempuri.org/IPersonaServicio/EditarResponse")>  _
        Function EditarAsync(ByVal Persona As PersonaServicio.DPersona) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/Eliminar", ReplyAction:="http://tempuri.org/IPersonaServicio/EliminarResponse")>  _
        Sub Eliminar(ByVal IdPersona As System.Guid)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/Eliminar", ReplyAction:="http://tempuri.org/IPersonaServicio/EliminarResponse")>  _
        Function EliminarAsync(ByVal IdPersona As System.Guid) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/Lista", ReplyAction:="http://tempuri.org/IPersonaServicio/ListaResponse")>  _
        Function Lista() As System.Collections.Generic.List(Of PersonaServicio.DPersona)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/Lista", ReplyAction:="http://tempuri.org/IPersonaServicio/ListaResponse")>  _
        Function ListaAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PersonaServicio.DPersona))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/Filtrar", ReplyAction:="http://tempuri.org/IPersonaServicio/FiltrarResponse")>  _
        Function Filtrar(ByVal Carnet As String, ByVal Id As String, ByVal Nombres As String, ByVal Apellidos As String) As System.Collections.Generic.List(Of PersonaServicio.DPersona)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/Filtrar", ReplyAction:="http://tempuri.org/IPersonaServicio/FiltrarResponse")>  _
        Function FiltrarAsync(ByVal Carnet As String, ByVal Id As String, ByVal Nombres As String, ByVal Apellidos As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PersonaServicio.DPersona))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/BuscarPorCarnet", ReplyAction:="http://tempuri.org/IPersonaServicio/BuscarPorCarnetResponse")>  _
        Function BuscarPorCarnet(ByVal Carnet As String) As PersonaServicio.DPersona
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/BuscarPorCarnet", ReplyAction:="http://tempuri.org/IPersonaServicio/BuscarPorCarnetResponse")>  _
        Function BuscarPorCarnetAsync(ByVal Carnet As String) As System.Threading.Tasks.Task(Of PersonaServicio.DPersona)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/BuscarPorIdentificacion", ReplyAction:="http://tempuri.org/IPersonaServicio/BuscarPorIdentificacionResponse")>  _
        Function BuscarPorIdentificacion(ByVal Id As String) As PersonaServicio.DPersona
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/BuscarPorIdentificacion", ReplyAction:="http://tempuri.org/IPersonaServicio/BuscarPorIdentificacionResponse")>  _
        Function BuscarPorIdentificacionAsync(ByVal Id As String) As System.Threading.Tasks.Task(Of PersonaServicio.DPersona)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/Busqueda", ReplyAction:="http://tempuri.org/IPersonaServicio/BusquedaResponse")>  _
        Function Busqueda(ByVal Persona As PersonaServicio.DPersona) As System.Collections.Generic.List(Of PersonaServicio.DPersona)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/Busqueda", ReplyAction:="http://tempuri.org/IPersonaServicio/BusquedaResponse")>  _
        Function BusquedaAsync(ByVal Persona As PersonaServicio.DPersona) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PersonaServicio.DPersona))
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/BuscarPorId", ReplyAction:="http://tempuri.org/IPersonaServicio/BuscarPorIdResponse")>  _
        Function BuscarPorId(ByVal IdPersona As System.Guid) As PersonaServicio.DPersona
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/BuscarPorId", ReplyAction:="http://tempuri.org/IPersonaServicio/BuscarPorIdResponse")>  _
        Function BuscarPorIdAsync(ByVal IdPersona As System.Guid) As System.Threading.Tasks.Task(Of PersonaServicio.DPersona)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/BuscarPorCarnetOIdentificacion", ReplyAction:="http://tempuri.org/IPersonaServicio/BuscarPorCarnetOIdentificacionResponse")>  _
        Function BuscarPorCarnetOIdentificacion(ByVal Id As String) As PersonaServicio.DPersona
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IPersonaServicio/BuscarPorCarnetOIdentificacion", ReplyAction:="http://tempuri.org/IPersonaServicio/BuscarPorCarnetOIdentificacionResponse")>  _
        Function BuscarPorCarnetOIdentificacionAsync(ByVal Id As String) As System.Threading.Tasks.Task(Of PersonaServicio.DPersona)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IPersonaServicioChannel
        Inherits PersonaServicio.IPersonaServicio, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PersonaServicioClient
        Inherits System.ServiceModel.ClientBase(Of PersonaServicio.IPersonaServicio)
        Implements PersonaServicio.IPersonaServicio
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub DoWork() Implements PersonaServicio.IPersonaServicio.DoWork
            MyBase.Channel.DoWork
        End Sub
        
        Public Function DoWorkAsync() As System.Threading.Tasks.Task Implements PersonaServicio.IPersonaServicio.DoWorkAsync
            Return MyBase.Channel.DoWorkAsync
        End Function
        
        Public Sub Guardar(ByVal Persona As PersonaServicio.DPersona) Implements PersonaServicio.IPersonaServicio.Guardar
            MyBase.Channel.Guardar(Persona)
        End Sub
        
        Public Function GuardarAsync(ByVal Persona As PersonaServicio.DPersona) As System.Threading.Tasks.Task Implements PersonaServicio.IPersonaServicio.GuardarAsync
            Return MyBase.Channel.GuardarAsync(Persona)
        End Function
        
        Public Sub Editar(ByVal Persona As PersonaServicio.DPersona) Implements PersonaServicio.IPersonaServicio.Editar
            MyBase.Channel.Editar(Persona)
        End Sub
        
        Public Function EditarAsync(ByVal Persona As PersonaServicio.DPersona) As System.Threading.Tasks.Task Implements PersonaServicio.IPersonaServicio.EditarAsync
            Return MyBase.Channel.EditarAsync(Persona)
        End Function
        
        Public Sub Eliminar(ByVal IdPersona As System.Guid) Implements PersonaServicio.IPersonaServicio.Eliminar
            MyBase.Channel.Eliminar(IdPersona)
        End Sub
        
        Public Function EliminarAsync(ByVal IdPersona As System.Guid) As System.Threading.Tasks.Task Implements PersonaServicio.IPersonaServicio.EliminarAsync
            Return MyBase.Channel.EliminarAsync(IdPersona)
        End Function
        
        Public Function Lista() As System.Collections.Generic.List(Of PersonaServicio.DPersona) Implements PersonaServicio.IPersonaServicio.Lista
            Return MyBase.Channel.Lista
        End Function
        
        Public Function ListaAsync() As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PersonaServicio.DPersona)) Implements PersonaServicio.IPersonaServicio.ListaAsync
            Return MyBase.Channel.ListaAsync
        End Function
        
        Public Function Filtrar(ByVal Carnet As String, ByVal Id As String, ByVal Nombres As String, ByVal Apellidos As String) As System.Collections.Generic.List(Of PersonaServicio.DPersona) Implements PersonaServicio.IPersonaServicio.Filtrar
            Return MyBase.Channel.Filtrar(Carnet, Id, Nombres, Apellidos)
        End Function
        
        Public Function FiltrarAsync(ByVal Carnet As String, ByVal Id As String, ByVal Nombres As String, ByVal Apellidos As String) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PersonaServicio.DPersona)) Implements PersonaServicio.IPersonaServicio.FiltrarAsync
            Return MyBase.Channel.FiltrarAsync(Carnet, Id, Nombres, Apellidos)
        End Function
        
        Public Function BuscarPorCarnet(ByVal Carnet As String) As PersonaServicio.DPersona Implements PersonaServicio.IPersonaServicio.BuscarPorCarnet
            Return MyBase.Channel.BuscarPorCarnet(Carnet)
        End Function
        
        Public Function BuscarPorCarnetAsync(ByVal Carnet As String) As System.Threading.Tasks.Task(Of PersonaServicio.DPersona) Implements PersonaServicio.IPersonaServicio.BuscarPorCarnetAsync
            Return MyBase.Channel.BuscarPorCarnetAsync(Carnet)
        End Function
        
        Public Function BuscarPorIdentificacion(ByVal Id As String) As PersonaServicio.DPersona Implements PersonaServicio.IPersonaServicio.BuscarPorIdentificacion
            Return MyBase.Channel.BuscarPorIdentificacion(Id)
        End Function
        
        Public Function BuscarPorIdentificacionAsync(ByVal Id As String) As System.Threading.Tasks.Task(Of PersonaServicio.DPersona) Implements PersonaServicio.IPersonaServicio.BuscarPorIdentificacionAsync
            Return MyBase.Channel.BuscarPorIdentificacionAsync(Id)
        End Function
        
        Public Function Busqueda(ByVal Persona As PersonaServicio.DPersona) As System.Collections.Generic.List(Of PersonaServicio.DPersona) Implements PersonaServicio.IPersonaServicio.Busqueda
            Return MyBase.Channel.Busqueda(Persona)
        End Function
        
        Public Function BusquedaAsync(ByVal Persona As PersonaServicio.DPersona) As System.Threading.Tasks.Task(Of System.Collections.Generic.List(Of PersonaServicio.DPersona)) Implements PersonaServicio.IPersonaServicio.BusquedaAsync
            Return MyBase.Channel.BusquedaAsync(Persona)
        End Function
        
        Public Function BuscarPorId(ByVal IdPersona As System.Guid) As PersonaServicio.DPersona Implements PersonaServicio.IPersonaServicio.BuscarPorId
            Return MyBase.Channel.BuscarPorId(IdPersona)
        End Function
        
        Public Function BuscarPorIdAsync(ByVal IdPersona As System.Guid) As System.Threading.Tasks.Task(Of PersonaServicio.DPersona) Implements PersonaServicio.IPersonaServicio.BuscarPorIdAsync
            Return MyBase.Channel.BuscarPorIdAsync(IdPersona)
        End Function
        
        Public Function BuscarPorCarnetOIdentificacion(ByVal Id As String) As PersonaServicio.DPersona Implements PersonaServicio.IPersonaServicio.BuscarPorCarnetOIdentificacion
            Return MyBase.Channel.BuscarPorCarnetOIdentificacion(Id)
        End Function
        
        Public Function BuscarPorCarnetOIdentificacionAsync(ByVal Id As String) As System.Threading.Tasks.Task(Of PersonaServicio.DPersona) Implements PersonaServicio.IPersonaServicio.BuscarPorCarnetOIdentificacionAsync
            Return MyBase.Channel.BuscarPorCarnetOIdentificacionAsync(Id)
        End Function
    End Class
End Namespace
